export function buildGuildSettingsRuntimeEffectsInput({
  currentGuild,
  currentGuildData,
  tab,
  membersLoaded,
  ranksLoaded,
  inviteLoaded,
  motdLoaded,
  openTraceId = null,
  onClose,
  refs,
  state,
  load,
  endPerfTraceAfterNextPaintFn,
} = {}) {
  return {
    currentGuild,
    currentGuildData,
    tab,
    membersLoaded,
    ranksLoaded,
    inviteLoaded,
    motdLoaded,
    openTraceId,
    onClose,
    refs,
    state,
    load,
    endPerfTraceAfterNextPaintFn,
  };
}

export function buildUseGuildSettingsControllerEffectsInput({
  currentGuild,
  currentGuildData,
  tab,
  membersLoaded,
  ranksLoaded,
  inviteLoaded,
  motdLoaded,
  openTraceId = null,
  onClose,
  loadingRef,
  completedOpenTraceIdsRef,
  setRanksFn,
  setRanksLoadedFn,
  setInviteCodeFn,
  setInviteLoadedFn,
  setMotdFn,
  setMotdLoadedFn,
  setMembersFn,
  setMembersLoadedFn,
  setGuildNameFn,
  setGuildDescFn,
  setGuildPublicFn,
  setGuildImageFn,
  setImagePreviewFn,
  loadMembers,
  loadRanks,
  loadInviteCode,
  loadMotd,
  endPerfTraceAfterNextPaintFn,
} = {}) {
  return buildGuildSettingsRuntimeEffectsInput({
    currentGuild,
    currentGuildData,
    tab,
    membersLoaded,
    ranksLoaded,
    inviteLoaded,
    motdLoaded,
    openTraceId,
    onClose,
    refs: {
      loadingRef,
      completedOpenTraceIdsRef,
    },
    state: {
      setRanksFn,
      setRanksLoadedFn,
      setInviteCodeFn,
      setInviteLoadedFn,
      setMotdFn,
      setMotdLoadedFn,
      setMembersFn,
      setMembersLoadedFn,
      setGuildNameFn,
      setGuildDescFn,
      setGuildPublicFn,
      setGuildImageFn,
      setImagePreviewFn,
    },
    load: {
      loadMembers,
      loadRanks,
      loadInviteCode,
      loadMotd,
    },
    endPerfTraceAfterNextPaintFn,
  });
}

export function buildGuildSettingsControllerActionInput({
  currentGuild,
  currentGuildData,
  guildName,
  guildDesc,
  guildPublic,
  guildImage,
  motd,
  newRankName,
  transferTarget,
  members,
  confirmDialog,
  flash,
  onClose,
  deps,
  state,
} = {}) {
  return {
    currentGuild,
    currentGuildName: currentGuildData?.name || '',
    guildName,
    guildDesc,
    guildPublic,
    guildImage,
    motd,
    newRankName,
    transferTarget,
    members,
    confirmDialog,
    flash,
    onClose,
    deps,
    state,
  };
}

export function buildUseGuildSettingsControllerActionsInput({
  currentGuild,
  currentGuildData = null,
  guildName = '',
  guildDesc = '',
  guildPublic = true,
  guildImage = '',
  motd = '',
  newRankName = '',
  transferTarget = '',
  members = [],
  confirmDialog = null,
  flash,
  onClose = () => {},
  fetchGuildDetailsFn,
  clearGuildFn,
  updateGuildFn,
  updateMotdFn,
  changeMemberRankFn,
  kickMemberFn,
  createRankFn,
  updateRankFn,
  deleteRankFn,
  regenerateInviteFn,
  transferLeadershipFn,
  disbandGuildFn,
  leaveGuildFn,
  loadMembersFn,
  loadRanksFn,
  setMotdLoadedFn = () => {},
  setUploadingImageFn = () => {},
  setGuildImageFn = () => {},
  setImagePreviewFn = () => {},
  setMembersFn = () => {},
  setConfirmDialogFn = () => {},
  setNewRankNameFn = () => {},
  setInviteCodeFn = () => {},
  setInviteLoadedFn = () => {},
} = {}) {
  return {
    currentGuild,
    currentGuildData,
    guildName,
    guildDesc,
    guildPublic,
    guildImage,
    motd,
    newRankName,
    transferTarget,
    members,
    confirmDialog,
    flash,
    onClose,
    fetchGuildDetailsFn,
    clearGuildFn,
    updateGuildFn,
    updateMotdFn,
    changeMemberRankFn,
    kickMemberFn,
    createRankFn,
    updateRankFn,
    deleteRankFn,
    regenerateInviteFn,
    transferLeadershipFn,
    disbandGuildFn,
    leaveGuildFn,
    loadMembersFn,
    loadRanksFn,
    setMotdLoadedFn,
    setUploadingImageFn,
    setGuildImageFn,
    setImagePreviewFn,
    setMembersFn,
    setConfirmDialogFn,
    setNewRankNameFn,
    setInviteCodeFn,
    setInviteLoadedFn,
  };
}

export function buildGuildSettingsControllerViewInput({
  shellState,
  currentGuild,
  currentGuildData,
  tab,
  error,
  success,
  confirmDialog,
  isTabPending,
  myRankOrder,
  members,
  ranks,
  inviteCode,
  transferTarget,
  editingRank,
  newRankName,
  guildName,
  guildDesc,
  guildPublic,
  guildImage,
  imagePreview,
  motd,
  uploadingImage,
  userId,
  isGuildMaster,
  onClose,
  onSelectTab,
  onDismissConfirmDialog,
  onAcceptConfirmDialog,
  onLeaveGuild,
  updateMemberPermissions,
  loadMembers,
  flash,
  handlers,
  setters,
} = {}) {
  return {
    shellState,
    currentGuild,
    currentGuildData,
    tab,
    error,
    success,
    confirmDialog,
    isTabPending,
    myRankOrder,
    members,
    ranks,
    inviteCode,
    transferTarget,
    editingRank,
    newRankName,
    guildName,
    guildDesc,
    guildPublic,
    guildImage,
    imagePreview,
    motd,
    uploadingImage,
    userId,
    isGuildMaster,
    onClose,
    onSelectTab,
    onDismissConfirmDialog,
    onAcceptConfirmDialog,
    onLeaveGuild,
    updateMemberPermissions,
    loadMembers,
    flash,
    handlers,
    setters,
  };
}

export function buildUseGuildSettingsControllerViewStateInput({
  shellState,
  currentGuild,
  currentGuildData,
  tab,
  error,
  success,
  confirmDialog,
  isTabPending,
  myRankOrder,
  members,
  ranks,
  inviteCode,
  transferTarget,
  editingRank,
  newRankName,
  guildName,
  guildDesc,
  guildPublic,
  guildImage,
  imagePreview,
  motd,
  uploadingImage,
  userId,
  isGuildMaster,
  onClose,
  onSelectTab,
  onDismissConfirmDialog,
  onAcceptConfirmDialog,
  onLeaveGuild,
  updateMemberPermissionsFn,
  loadMembersFn,
  flash,
  handlers,
  setters,
} = {}) {
  return {
    shellState,
    currentGuild,
    currentGuildData,
    tab,
    error,
    success,
    confirmDialog,
    isTabPending,
    myRankOrder,
    members,
    ranks,
    inviteCode,
    transferTarget,
    editingRank,
    newRankName,
    guildName,
    guildDesc,
    guildPublic,
    guildImage,
    imagePreview,
    motd,
    uploadingImage,
    userId,
    isGuildMaster,
    onClose,
    onSelectTab,
    onDismissConfirmDialog,
    onAcceptConfirmDialog,
    onLeaveGuild,
    updateMemberPermissionsFn,
    loadMembersFn,
    flash,
    handlers,
    setters,
  };
}
