export function buildGuildSettingsActionOptions({
  currentGuild,
  currentGuildName = '',
  guildName,
  guildDesc,
  guildPublic,
  guildImage,
  motd,
  newRankName,
  transferTarget,
  members,
  confirmDialog,
  flash,
  onClose,
  deps,
  state,
} = {}) {
  return {
    currentGuild,
    currentGuildName,
    guildName,
    guildDesc,
    guildPublic,
    guildImage,
    motd,
    newRankName,
    transferTarget,
    members,
    confirmDialog,
    flash,
    onClose,
    deps,
    state,
  };
}

export function buildGuildSettingsControllerViewState({
  shellState,
  currentGuild,
  currentGuildData,
  tab,
  error,
  success,
  confirmDialog,
  isTabPending,
  myRankOrder,
  members,
  ranks,
  inviteCode,
  transferTarget,
  editingRank,
  newRankName,
  guildName,
  guildDesc,
  guildPublic,
  guildImage,
  imagePreview,
  motd,
  uploadingImage,
  userId,
  isGuildMaster,
  onClose,
  onSelectTab,
  onDismissConfirmDialog,
  onAcceptConfirmDialog,
  onLeaveGuild,
  updateMemberPermissions,
  loadMembers,
  flash,
  handlers,
  setters,
} = {}) {
  return {
    ...shellState,
    currentGuild,
    currentGuildData,
    tab,
    error,
    success,
    confirmDialog,
    isTabPending,
    myRankOrder,
    members,
    ranks,
    inviteCode,
    transferTarget,
    editingRank,
    newRankName,
    guildName,
    guildDesc,
    guildPublic,
    guildImage,
    imagePreview,
    motd,
    uploadingImage,
    userId,
    onClose,
    onSelectTab,
    onDismissConfirmDialog,
    onAcceptConfirmDialog,
    overviewProps: {
      guildName,
      setGuildName: setters.setGuildName,
      guildDesc,
      setGuildDesc: setters.setGuildDesc,
      guildPublic,
      setGuildPublic: setters.setGuildPublic,
      guildImage,
      imagePreview,
      onImageSelect: handlers.onImageSelect,
      onRemoveImage: handlers.onRemoveImage,
      uploadingImage,
      motd,
      setMotd: setters.setMotd,
      onSaveOverview: handlers.onSaveOverview,
      onSaveMotd: handlers.onSaveMotd,
      canManageTheme: shellState.canManageTheme,
      canModifyMotd: shellState.canModifyMotd,
      readOnly: shellState.readOnly,
    },
    membersProps: {
      members,
      ranks,
      myRankOrder,
      onChangeRank: handlers.onChangeRank,
      onKick: handlers.onKick,
      userId,
      showControls: shellState.showMemberControls,
      isGuildMaster,
      guildId: currentGuild,
      onUpdatePermissions: updateMemberPermissions,
      onRefreshMembers: () => loadMembers({ force: true }),
      flash,
    },
    ranksProps: {
      ranks,
      myRankOrder,
      editingRank,
      setEditingRank: setters.setEditingRank,
      newRankName,
      setNewRankName: setters.setNewRankName,
      onCreateRank: handlers.onCreateRank,
      onUpdateRank: handlers.onUpdateRank,
      onDeleteRank: handlers.onDeleteRank,
      canSetPerms: shellState.canSetPerms,
    },
    inviteProps: {
      inviteCode,
      onRegenerate: handlers.onRegenerateInvite,
      canInvite: shellState.canInvite,
    },
    adminProps: {
      members,
      transferTarget,
      setTransferTarget: setters.setTransferTarget,
      onTransfer: handlers.onTransfer,
      onDisband: handlers.onDisband,
      userId,
    },
    onLeaveGuild,
  };
}
