import {
  buildUseGuildSettingsControllerActionsInput,
  buildUseGuildSettingsControllerViewStateInput,
} from './guildSettingsControllerInputs.mjs';
import { useGuildSettingsControllerActions } from './useGuildSettingsControllerActions.mjs';
import { useGuildSettingsControllerViewState } from './useGuildSettingsControllerViewState.mjs';

export function useGuildSettingsControllerActionView({
  currentGuild = null,
  currentGuildData = null,
  userId = null,
  onClose = () => {},
  state = {},
  derived = {},
  deps = {},
  support = {},
} = {}) {
  const {
    myRankOrder = 0,
    isGuildMaster = false,
    shellState = {},
  } = derived;

  const {
    fetchGuildDetailsFn = async () => {},
    clearGuildFn = () => {},
    updateGuildFn = async () => {},
    disbandGuildFn = async () => {},
    transferLeadershipFn = async () => {},
    regenerateInviteFn = async () => '',
    changeMemberRankFn = async () => {},
    kickMemberFn = async () => {},
    createRankFn = async () => {},
    updateRankFn = async () => {},
    deleteRankFn = async () => {},
    updateMotdFn = async () => {},
    updateMemberPermissionsFn = async () => {},
    leaveGuildFn = async () => {},
  } = deps;

  const actions = useGuildSettingsControllerActions(buildUseGuildSettingsControllerActionsInput({
    currentGuild,
    currentGuildData,
    guildName: state.guildName,
    guildDesc: state.guildDesc,
    guildPublic: state.guildPublic,
    guildImage: state.guildImage,
    motd: state.motd,
    newRankName: state.newRankName,
    transferTarget: state.transferTarget,
    members: state.members,
    confirmDialog: state.confirmDialog,
    flash: support.flash,
    onClose,
    fetchGuildDetailsFn,
    clearGuildFn,
    updateGuildFn,
    updateMotdFn,
    changeMemberRankFn,
    kickMemberFn,
    createRankFn,
    updateRankFn,
    deleteRankFn,
    regenerateInviteFn,
    transferLeadershipFn,
    disbandGuildFn,
    leaveGuildFn,
    loadMembersFn: support.loadMembers,
    loadRanksFn: support.loadRanks,
    setMotdLoadedFn: state.setMotdLoaded,
    setUploadingImageFn: state.setUploadingImage,
    setGuildImageFn: state.setGuildImage,
    setImagePreviewFn: state.setImagePreview,
    setMembersFn: state.setMembers,
    setConfirmDialogFn: state.setConfirmDialog,
    setNewRankNameFn: state.setNewRankName,
    setInviteCodeFn: state.setInviteCode,
    setInviteLoadedFn: state.setInviteLoaded,
  }));

  return useGuildSettingsControllerViewState(buildUseGuildSettingsControllerViewStateInput({
    shellState,
    currentGuild,
    currentGuildData,
    tab: state.tab,
    error: state.error,
    success: state.success,
    confirmDialog: state.confirmDialog,
    isTabPending: state.isTabPending,
    myRankOrder,
    members: state.members,
    ranks: state.ranks,
    inviteCode: state.inviteCode,
    transferTarget: state.transferTarget,
    editingRank: state.editingRank,
    newRankName: state.newRankName,
    guildName: state.guildName,
    guildDesc: state.guildDesc,
    guildPublic: state.guildPublic,
    guildImage: state.guildImage,
    imagePreview: state.imagePreview,
    motd: state.motd,
    uploadingImage: state.uploadingImage,
    userId,
    isGuildMaster,
    onClose,
    onSelectTab: support.onSelectTab,
    onDismissConfirmDialog: actions.onDismissConfirmDialog,
    onAcceptConfirmDialog: actions.onAcceptConfirmDialog,
    onLeaveGuild: actions.onLeaveGuild,
    updateMemberPermissionsFn,
    loadMembersFn: support.loadMembers,
    flash: support.flash,
    handlers: {
      onSaveOverview: actions.onSaveOverview,
      onSaveMotd: actions.onSaveMotd,
      onImageSelect: actions.onImageSelect,
      onRemoveImage: actions.onRemoveImage,
      onChangeRank: actions.onChangeRank,
      onKick: actions.onKick,
      onCreateRank: actions.onCreateRank,
      onUpdateRank: actions.onUpdateRank,
      onDeleteRank: actions.onDeleteRank,
      onRegenerateInvite: actions.onRegenerateInvite,
      onTransfer: actions.onTransfer,
      onDisband: actions.onDisband,
    },
    setters: {
      setGuildName: state.setGuildName,
      setGuildDesc: state.setGuildDesc,
      setGuildPublic: state.setGuildPublic,
      setMotd: state.setMotd,
      setEditingRank: state.setEditingRank,
      setNewRankName: state.setNewRankName,
      setTransferTarget: state.setTransferTarget,
    },
  }));
}
