import { useMemo } from 'react';

import { buildGuildSettingsControllerViewState } from './guildSettingsControllerBindings.mjs';
import { buildGuildSettingsControllerViewInput } from './guildSettingsControllerInputs.mjs';

export function useGuildSettingsControllerViewState({
  shellState,
  currentGuild,
  currentGuildData = null,
  tab = 'Overview',
  error = '',
  success = '',
  confirmDialog = null,
  isTabPending = false,
  myRankOrder = null,
  members = [],
  ranks = [],
  inviteCode = '',
  transferTarget = '',
  editingRank = null,
  newRankName = '',
  guildName = '',
  guildDesc = '',
  guildPublic = true,
  guildImage = '',
  imagePreview = null,
  motd = '',
  uploadingImage = false,
  userId = null,
  isGuildMaster = false,
  onClose = () => {},
  onSelectTab = () => {},
  onDismissConfirmDialog = () => {},
  onAcceptConfirmDialog = () => {},
  onLeaveGuild = () => {},
  updateMemberPermissionsFn,
  loadMembersFn,
  flash,
  handlers = {},
  setters = {},
} = {}) {
  return useMemo(() => buildGuildSettingsControllerViewState(buildGuildSettingsControllerViewInput({
    shellState,
    currentGuild,
    currentGuildData,
    tab,
    error,
    success,
    confirmDialog,
    isTabPending,
    myRankOrder,
    members,
    ranks,
    inviteCode,
    transferTarget,
    editingRank,
    newRankName,
    guildName,
    guildDesc,
    guildPublic,
    guildImage,
    imagePreview,
    motd,
    uploadingImage,
    userId,
    isGuildMaster,
    onClose,
    onSelectTab,
    onDismissConfirmDialog,
    onAcceptConfirmDialog,
    onLeaveGuild,
    updateMemberPermissions: updateMemberPermissionsFn,
    loadMembers: loadMembersFn,
    flash,
    handlers,
    setters,
  })), [
    shellState,
    currentGuild,
    currentGuildData,
    tab,
    error,
    success,
    confirmDialog,
    isTabPending,
    myRankOrder,
    members,
    ranks,
    inviteCode,
    transferTarget,
    editingRank,
    newRankName,
    guildName,
    guildDesc,
    guildPublic,
    guildImage,
    imagePreview,
    motd,
    uploadingImage,
    userId,
    isGuildMaster,
    onClose,
    onSelectTab,
    onDismissConfirmDialog,
    onAcceptConfirmDialog,
    onLeaveGuild,
    updateMemberPermissionsFn,
    loadMembersFn,
    flash,
    handlers,
    setters,
  ]);
}
