import { useMemo } from 'react';

import { uploadFile } from '../../api';
import { createGuildSettingsControllerActions } from './guildSettingsActionFlow.mjs';
import { buildGuildSettingsActionOptions } from './guildSettingsControllerBindings.mjs';
import { buildGuildSettingsControllerActionInput } from './guildSettingsControllerInputs.mjs';

export function useGuildSettingsControllerActions({
  currentGuild,
  currentGuildData = null,
  guildName = '',
  guildDesc = '',
  guildPublic = true,
  guildImage = '',
  motd = '',
  newRankName = '',
  transferTarget = '',
  members = [],
  confirmDialog = null,
  flash,
  onClose = () => {},
  fetchGuildDetailsFn,
  clearGuildFn,
  updateGuildFn,
  updateMotdFn,
  changeMemberRankFn,
  kickMemberFn,
  createRankFn,
  updateRankFn,
  deleteRankFn,
  regenerateInviteFn,
  transferLeadershipFn,
  disbandGuildFn,
  leaveGuildFn,
  loadMembersFn,
  loadRanksFn,
  setMotdLoadedFn = () => {},
  setUploadingImageFn = () => {},
  setGuildImageFn = () => {},
  setImagePreviewFn = () => {},
  setMembersFn = () => {},
  setConfirmDialogFn = () => {},
  setNewRankNameFn = () => {},
  setInviteCodeFn = () => {},
  setInviteLoadedFn = () => {},
} = {}) {
  return useMemo(() => createGuildSettingsControllerActions(buildGuildSettingsActionOptions(
    buildGuildSettingsControllerActionInput({
      currentGuild,
      currentGuildData,
      guildName,
      guildDesc,
      guildPublic,
      guildImage,
      motd,
      newRankName,
      transferTarget,
      members,
      confirmDialog,
      flash,
      onClose,
      deps: {
        updateGuildFn,
        fetchGuildDetailsFn,
        updateMotdFn,
        uploadGuildImageFileFn: uploadFile,
        createObjectUrlFn: URL.createObjectURL,
        revokeObjectUrlFn: URL.revokeObjectURL,
        changeMemberRankFn,
        kickMemberFn,
        createRankFn,
        updateRankFn,
        deleteRankFn,
        regenerateInviteFn,
        transferLeadershipFn,
        disbandGuildFn,
        leaveGuildFn,
        loadMembersFn,
        loadRanksFn,
        clearGuildFn,
      },
      state: {
        setMotdLoadedFn,
        setUploadingImageFn,
        setGuildImageFn,
        setImagePreviewFn,
        setMembersFn,
        setConfirmDialogFn,
        setNewRankNameFn,
        setInviteCodeFn,
        setInviteLoadedFn,
      },
    })
  )), [
    changeMemberRankFn,
    clearGuildFn,
    confirmDialog,
    createRankFn,
    currentGuild,
    currentGuildData?.name,
    deleteRankFn,
    disbandGuildFn,
    fetchGuildDetailsFn,
    flash,
    guildDesc,
    guildImage,
    guildName,
    guildPublic,
    kickMemberFn,
    leaveGuildFn,
    loadMembersFn,
    loadRanksFn,
    members,
    motd,
    newRankName,
    onClose,
    regenerateInviteFn,
    transferLeadershipFn,
    transferTarget,
    updateGuildFn,
    updateMotdFn,
    updateRankFn,
  ]);
}
