const ERROR_CODES = {
  NOT_GUILD_MEMBER: 'NOT_GUILD_MEMBER',
  GUILD_PERMISSION_DENIED: 'GUILD_PERMISSION_DENIED',
  GUILDCHAT_LISTEN_FORBIDDEN: 'GUILDCHAT_LISTEN_FORBIDDEN',
  GUILDCHAT_SPEAK_FORBIDDEN: 'GUILDCHAT_SPEAK_FORBIDDEN',
  INVALID_GUILDCHAT_PAYLOAD: 'INVALID_GUILDCHAT_PAYLOAD',
  INVALID_GUILDCHAT_MENTION_PAYLOAD: 'INVALID_GUILDCHAT_MENTION_PAYLOAD',
  INVALID_VOICE_PAYLOAD: 'INVALID_VOICE_PAYLOAD',
};

module.exports = {
  ERROR_CODES,
};
