export const styles = {
  container: {
    animation: 'fadeIn 0.3s ease-out',
  },
  header: {
    textAlign: 'center',
    marginBottom: 24,
    paddingTop: 8,
  },
  brand: {
    fontSize: 28,
    fontWeight: 700,
    fontFamily: "'Geist', sans-serif",
    letterSpacing: '-1px',
    color: '#40FF40',
    textShadow: '0 0 12px rgba(64, 255, 64, 0.4)',
    marginBottom: 12,
  },
  introText: {
    color: 'rgba(255, 255, 255, 0.55)',
    fontSize: 13,
    lineHeight: 1.5,
    margin: 0,
  },
  primerCallout: {
    padding: '14px 16px',
    marginBottom: 16,
    borderRadius: 12,
    border: '1px solid rgba(64, 255, 64, 0.12)',
    background: 'rgba(64, 255, 64, 0.05)',
  },
  primerCalloutText: {
    color: '#dfe8df',
    fontSize: 12,
    lineHeight: 1.6,
    margin: 0,
  },
  primerToggle: {
    width: '100%',
    background: 'none',
    border: '1px solid rgba(64, 255, 64, 0.15)',
    borderRadius: 8,
    color: 'rgba(255, 255, 255, 0.78)',
    cursor: 'pointer',
    fontSize: 12,
    padding: '10px 12px',
    textAlign: 'left',
  },
  primerPanel: {
    padding: '14px 16px',
    marginBottom: 16,
    borderRadius: 12,
    border: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'rgba(255, 255, 255, 0.03)',
  },
  primerPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: 10,
  },
  primerPanelTitle: {
    color: '#dfe8df',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.6px',
    textTransform: 'uppercase',
    margin: 0,
  },
  primerLead: {
    color: '#dfe8df',
    fontSize: 12,
    lineHeight: 1.6,
    margin: '0 0 10px',
  },
  primerParagraph: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 12,
    lineHeight: 1.6,
    margin: '0 0 8px',
  },
  primerMutedParagraph: {
    color: 'rgba(255, 255, 255, 0.55)',
    fontSize: 12,
    lineHeight: 1.6,
  },
  primerSuccess: {
    color: '#40FF40',
  },
  primerDanger: {
    color: '#ff9b9b',
  },
  primerActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: 12,
  },
  primerDismissBtn: {
    background: 'rgba(64, 255, 64, 0.08)',
    border: '1px solid rgba(64, 255, 64, 0.16)',
    borderRadius: 8,
    color: '#dfe8df',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 600,
    padding: '8px 12px',
  },
  identityRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    marginBottom: 16,
  },
  identityMeta: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    flex: 1,
  },
  imageButton: {
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid rgba(64, 255, 64, 0.15)',
    background: 'transparent',
    color: 'rgba(255, 255, 255, 0.78)',
    cursor: 'pointer',
    fontSize: 12,
    textAlign: 'left',
  },
  removeImageButton: {
    padding: '0',
    border: 'none',
    background: 'none',
    color: 'rgba(255, 255, 255, 0.45)',
    cursor: 'pointer',
    fontSize: 11,
    textAlign: 'left',
  },
  imageHelpText: {
    color: 'rgba(255, 255, 255, 0.28)',
    fontSize: 11,
    lineHeight: 1.5,
    margin: 0,
  },
  fieldLabel: {
    display: 'block',
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 11,
    letterSpacing: '1px',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  textareaInput: {
    fontSize: 13,
    minHeight: 72,
    resize: 'vertical',
  },
  generateButton: {
    width: '100%',
    padding: '14px 0',
    borderRadius: 8,
    border: 'none',
    fontSize: 14,
    fontWeight: 600,
    transition: 'all 0.2s',
    boxShadow: '0 0 16px rgba(64, 255, 64, 0.15)',
  },
  generatedWarning: {
    display: 'flex',
    gap: 12,
    alignItems: 'flex-start',
    padding: '14px 16px',
    marginBottom: 16,
    borderRadius: 12,
    border: '1px solid rgba(255, 99, 99, 0.2)',
    background: 'rgba(255, 99, 99, 0.1)',
  },
  generatedWarningIconWrap: {
    flexShrink: 0,
    width: 36,
    height: 36,
    borderRadius: 10,
    background: 'rgba(255, 255, 255, 0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  generatedWarningTitle: {
    color: '#ff9b9b',
    fontSize: 13,
    fontWeight: 700,
    margin: '0 0 6px',
  },
  generatedWarningText: {
    color: 'rgba(255, 225, 225, 0.82)',
    fontSize: 12,
    lineHeight: 1.55,
    margin: 0,
  },
  keyBlock: {
    marginBottom: 12,
  },
  keyHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  keyLabel: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 11,
    letterSpacing: '1px',
    textTransform: 'uppercase',
    margin: 0,
  },
  keyActionGroup: {
    display: 'flex',
    gap: 8,
  },
  keyCopyButton: {
    background: 'none',
    border: '1px solid rgba(64, 255, 64, 0.15)',
    borderRadius: 8,
    color: 'rgba(255, 255, 255, 0.7)',
    cursor: 'pointer',
    fontSize: 11,
    padding: '5px 8px',
  },
  keyToggleButton: {
    background: 'none',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    color: 'rgba(255, 255, 255, 0.7)',
    cursor: 'pointer',
    fontSize: 11,
    padding: '5px 8px',
  },
  keyValue: {
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 1.5,
    wordBreak: 'break-all',
  },
  copyState: {
    fontSize: 11,
    marginTop: 0,
    marginBottom: 12,
    textAlign: 'center',
  },
  error: {
    color: '#ff4757',
    fontSize: 12,
    marginBottom: 12,
    wordBreak: 'break-word',
  },
  submitButton: {
    width: '100%',
    padding: '12px 0',
    borderRadius: 8,
    border: 'none',
    fontSize: 14,
    fontWeight: 600,
    transition: 'all 0.2s',
    marginBottom: 10,
  },
  browserButton: {
    width: '100%',
    background: 'none',
    border: '1px solid rgba(64, 255, 64, 0.15)',
    borderRadius: 8,
    color: 'rgba(255, 255, 255, 0.7)',
    cursor: 'pointer',
    fontSize: 12,
    padding: '10px 12px',
  },
};

