export const styles = {
  container: {
    animation: 'fadeIn 0.3s ease-out',
  },
  centeredHeader: {
    textAlign: 'center',
    marginBottom: 32,
  },
  centeredHeaderWithTopPadding: {
    textAlign: 'center',
    marginBottom: 28,
    paddingTop: 8,
  },
  brand: {
    fontSize: 28,
    fontWeight: 700,
    fontFamily: "'Geist', sans-serif",
    letterSpacing: '-1px',
    color: '#40FF40',
    textShadow: '0 0 12px rgba(64, 255, 64, 0.4)',
    marginBottom: 12,
  },
  introText: {
    color: 'rgba(255, 255, 255, 0.55)',
    fontSize: 13,
    lineHeight: 1.5,
    margin: 0,
  },
  primaryButton: {
    width: '100%',
    padding: '14px 0',
    borderRadius: 8,
    border: 'none',
    background: '#40FF40',
    color: '#050705',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    boxShadow: '0 0 16px rgba(64, 255, 64, 0.15)',
  },
  secondaryButton: {
    width: '100%',
    padding: '14px 0',
    borderRadius: 8,
    border: '1px solid rgba(64, 255, 64, 0.15)',
    background: 'transparent',
    color: '#e0e8e0',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  welcomeFootnote: {
    color: 'rgba(255, 255, 255, 0.28)',
    fontSize: 11,
    lineHeight: 1.5,
    margin: 0,
    textAlign: 'center',
  },
  serverToggle: {
    width: '100%',
    marginTop: 12,
    background: 'none',
    border: 'none',
    color: 'rgba(64, 255, 64, 0.25)',
    fontSize: 11,
    cursor: 'pointer',
    letterSpacing: '0.3px',
    transition: 'color 0.2s',
  },
  insecureServerWarning: {
    marginTop: 8,
    padding: '8px 12px',
    borderRadius: 6,
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    fontSize: 11,
    color: '#ef4444',
    lineHeight: 1.4,
  },
  iconBadge: {
    margin: '0 auto 16px',
    width: 48,
    height: 48,
    borderRadius: 12,
    background: 'rgba(64, 255, 64, 0.06)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionLabel: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: '2px',
    textTransform: 'uppercase',
  },
  warningCard: {
    display: 'flex',
    gap: 12,
    alignItems: 'flex-start',
    padding: '14px 16px',
    marginBottom: 16,
    borderRadius: 12,
    border: '1px solid rgba(255, 99, 99, 0.2)',
    background: 'rgba(255, 99, 99, 0.1)',
  },
  warningIconWrap: {
    flexShrink: 0,
    width: 36,
    height: 36,
    borderRadius: 10,
    background: 'rgba(255, 255, 255, 0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  warningTitle: {
    color: '#ff9b9b',
    fontSize: 13,
    fontWeight: 700,
    margin: '0 0 6px',
  },
  warningText: {
    color: 'rgba(255, 225, 225, 0.82)',
    fontSize: 12,
    lineHeight: 1.55,
    margin: 0,
  },
  helperText: {
    color: 'rgba(255, 255, 255, 0.3)',
    fontSize: 11,
    marginBottom: 16,
    lineHeight: 1.5,
  },
  error: {
    color: '#ff4757',
    fontSize: 12,
    marginBottom: 12,
    wordBreak: 'break-word',
  },
  submitButton: {
    width: '100%',
    padding: '12px 0',
    borderRadius: 8,
    border: 'none',
    fontSize: 14,
    fontWeight: 600,
    transition: 'all 0.2s',
  },
};

