const UNIVERSAL_GUILD_CHAT_PERMISSION_KEYS = ['guild_chat_speak', 'guild_chat_listen'];
const NON_DELEGABLE_GUILD_PERMISSION_KEYS = ['disband_guild', 'transfer_leadership'];

const DEFAULT_GUILD_RANK_PERMISSIONS = {
  guildMaster: {
    invite_member: true,
    remove_member: true,
    promote_demote: true,
    manage_applications: true,
    guild_chat_speak: true,
    guild_chat_listen: true,
    officer_chat: true,
    modify_motd: true,
    create_delete_events: true,
    edit_public_note: true,
    edit_officer_note: true,
    view_officer_note: true,
    view_asset_dump: true,
    upload_files: true,
    download_files: true,
    delete_files: true,
    manage_storage: true,
    modify_rank_names: true,
    set_permissions: true,
    manage_rooms: true,
    manage_theme: true,
  },
  officer: {
    invite_member: true,
    remove_member: true,
    promote_demote: true,
    manage_applications: true,
    guild_chat_speak: true,
    guild_chat_listen: true,
    officer_chat: true,
    modify_motd: false,
    create_delete_events: true,
    edit_public_note: true,
    edit_officer_note: true,
    view_officer_note: true,
    view_asset_dump: true,
    upload_files: true,
    download_files: true,
    delete_files: true,
    manage_storage: true,
    modify_rank_names: false,
    set_permissions: false,
    manage_rooms: true,
    manage_theme: true,
  },
  veteran: {
    invite_member: true,
    remove_member: false,
    promote_demote: false,
    manage_applications: false,
    guild_chat_speak: true,
    guild_chat_listen: true,
    officer_chat: false,
    modify_motd: false,
    create_delete_events: false,
    edit_public_note: true,
    edit_officer_note: false,
    view_officer_note: false,
    view_asset_dump: true,
    upload_files: true,
    download_files: true,
    delete_files: false,
    manage_storage: false,
    modify_rank_names: false,
    set_permissions: false,
    manage_rooms: false,
    manage_theme: false,
  },
  member: {
    invite_member: false,
    remove_member: false,
    promote_demote: false,
    manage_applications: false,
    guild_chat_speak: true,
    guild_chat_listen: true,
    officer_chat: false,
    modify_motd: false,
    create_delete_events: false,
    edit_public_note: true,
    edit_officer_note: false,
    view_officer_note: false,
    view_asset_dump: true,
    upload_files: false,
    download_files: true,
    delete_files: false,
    manage_storage: false,
    modify_rank_names: false,
    set_permissions: false,
    manage_rooms: false,
    manage_theme: false,
  },
  initiate: {
    invite_member: false,
    remove_member: false,
    promote_demote: false,
    manage_applications: false,
    guild_chat_speak: true,
    guild_chat_listen: true,
    officer_chat: false,
    modify_motd: false,
    create_delete_events: false,
    edit_public_note: false,
    edit_officer_note: false,
    view_officer_note: false,
    view_asset_dump: true,
    upload_files: false,
    download_files: false,
    delete_files: false,
    manage_storage: false,
    modify_rank_names: false,
    set_permissions: false,
    manage_rooms: false,
    manage_theme: false,
  },
};

const GUILD_MASTER_PERMISSION_KEYS = Object.keys(DEFAULT_GUILD_RANK_PERMISSIONS.guildMaster || {});
const KNOWN_GUILD_PERMISSION_KEYS = Array.from(
  new Set([
    ...Object.keys(DEFAULT_GUILD_RANK_PERMISSIONS.guildMaster || {}),
    ...Object.keys(DEFAULT_GUILD_RANK_PERMISSIONS.officer || {}),
    ...Object.keys(DEFAULT_GUILD_RANK_PERMISSIONS.veteran || {}),
    ...Object.keys(DEFAULT_GUILD_RANK_PERMISSIONS.member || {}),
    ...Object.keys(DEFAULT_GUILD_RANK_PERMISSIONS.initiate || {}),
    ...UNIVERSAL_GUILD_CHAT_PERMISSION_KEYS,
  ])
);

module.exports = {
  DEFAULT_GUILD_RANK_PERMISSIONS,
  GUILD_MASTER_PERMISSION_KEYS,
  KNOWN_GUILD_PERMISSION_KEYS,
  NON_DELEGABLE_GUILD_PERMISSION_KEYS,
  UNIVERSAL_GUILD_CHAT_PERMISSION_KEYS,
};
