export const styles = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.7)',
    backdropFilter: 'blur(4px)',
    WebkitBackdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    background: 'var(--bg-secondary)',
    borderRadius: 12,
    border: '1px solid var(--border)',
    boxShadow: '0 16px 48px rgba(0, 0, 0, 0.5)',
    width: 440,
    maxWidth: '90vw',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column',
    animation: 'fadeIn 0.2s ease-out',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px 8px',
  },
  title: {
    fontSize: 16,
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: 0,
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--text-muted)',
    fontSize: 22,
    cursor: 'pointer',
    padding: '0 4px',
    lineHeight: 1,
  },
  tabs: {
    display: 'flex',
    gap: 0,
    padding: '0 20px',
    borderBottom: '1px solid var(--border)',
  },
  tabBtn: {
    background: 'none',
    border: 'none',
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    transition: 'color 0.15s',
  },
  badge: {
    fontSize: 10,
    fontWeight: 700,
    padding: '1px 6px',
    borderRadius: 10,
    minWidth: 18,
    textAlign: 'center',
  },
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px 16px 16px',
  },
  searchInput: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    fontSize: 13,
    outline: 'none',
    boxSizing: 'border-box',
  },
  searchMsg: {
    fontSize: 11,
    marginTop: 4,
  },
  resultRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '8px',
    borderRadius: 8,
  },
  requestRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 8px',
    borderRadius: 8,
  },
  contactRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '8px',
    borderRadius: 8,
    cursor: 'pointer',
    width: '100%',
    border: 'none',
    color: 'inherit',
    fontSize: 'inherit',
    transition: 'background 0.15s',
  },
  nameText: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  npubText: {
    fontSize: 11,
    color: 'var(--text-muted)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: 'monospace',
  },
  aboutText: {
    fontSize: 11,
    color: 'var(--text-muted)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  actionBtn: {
    padding: '5px 12px',
    borderRadius: 6,
    border: 'none',
    background: 'var(--accent, #40FF40)',
    color: '#000',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    flexShrink: 0,
    whiteSpace: 'nowrap',
  },
  secondaryActionBtn: {
    background: 'transparent',
    border: '1px solid var(--border)',
    color: 'var(--text-secondary)',
  },
  inviteActionBtn: {
    background: 'var(--bg-tertiary, #333)',
    color: 'var(--text-primary)',
  },
  emptyState: {
    padding: 40,
    textAlign: 'center',
    color: 'var(--text-muted)',
    fontSize: 13,
  },
  profileCard: {
    margin: '0 8px 8px',
    padding: 14,
    borderRadius: 8,
    background: 'var(--bg-primary)',
    border: '1px solid var(--border)',
  },
  inviteMenu: {
    position: 'absolute',
    right: 0,
    top: '100%',
    marginTop: 4,
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    boxShadow: '0 8px 24px rgba(0,0,0,0.4)',
    zIndex: 10,
    overflow: 'hidden',
    minWidth: 160,
  },
  inviteMenuItem: {
    display: 'block',
    width: '100%',
    padding: '8px 14px',
    background: 'none',
    border: 'none',
    color: 'var(--text-primary)',
    fontSize: 12,
    textAlign: 'left',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  cardBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 10px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'transparent',
    color: 'var(--text-secondary)',
    fontSize: 11,
    cursor: 'pointer',
    transition: 'border-color 0.15s',
  },
  mutedLabel: {
    fontSize: 11,
    color: 'var(--text-muted)',
    flexShrink: 0,
  },
  accentLabel: {
    fontSize: 11,
    color: 'var(--accent, #40FF40)',
    flexShrink: 0,
  },
  profileHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  profileName: {
    fontSize: 15,
    fontWeight: 600,
    color: 'var(--text-primary)',
    marginBottom: 2,
  },
  profileMonospaceText: {
    fontSize: 11,
    color: 'var(--text-muted)',
    fontFamily: 'monospace',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  profileActions: {
    display: 'flex',
    gap: 6,
  },
  chevron: {
    flexShrink: 0,
    opacity: 0.3,
    transition: 'transform 0.15s',
  },
};
