export function buildUseMessagesFlowContracts({
  conversation = null,
  runMessageReloadFlowFn = () => {},
  getConversationCacheKeyFn = () => '',
  messageBelongsToConversationFn = () => false,
  fetchConversationMessagesFn = async () => [],
  cacheConversationStateFn = () => {},
  replaceMessagesFromSnapshotFn = () => [],
  mergeMessagesByIdFn = () => [],
  debugRoomOpenLogFn = () => {},
  addPerfPhaseFn = () => {},
  sortMessagesChronologicallyFn = (messages) => messages,
  syncConversationRoomSenderKeysFn = async () => {},
  dmUnavailableError = null,
  retryFailedConversationMessagesFn = async () => {},
  tryDecryptMessageFn = async () => null,
  getMessageTimestampValueFn = () => 0,
  createMessageSendActionFn = () => {},
  isE2EInitializedFn = () => false,
  hasKnownNpubFn = () => false,
  encryptGroupMessageFn = async () => null,
  encryptDirectMessageFn = async () => null,
  createConversationTimestampFn = () => null,
  appendOrReplaceMessageFn = () => [],
  updateCachedConversationStateFn = () => {},
  sanitizeCachedAttachmentsFn = (attachments) => attachments,
  persistDecryptedMessageFn = () => {},
  revokeAttachmentPreviewUrlsFn = () => {},
  createLoadMoreMessagesActionFn = () => {},
  prependOlderMessagesFn = () => [],
  createEditMessageActionFn = () => {},
  createDeleteMessageActionFn = () => {},
} = {}) {
  return {
    runMessageReloadFlowFn,
    getConversationCacheKeyFn,
    messageBelongsToConversationFn,
    fetchConversationMessagesFn,
    cacheConversationStateFn,
    replaceMessagesFromSnapshotFn,
    mergeMessagesByIdFn,
    debugRoomOpenLogFn: (phase, details) => {
      if (phase === 'messages-committed' && conversation?.type === 'room') {
        window.requestAnimationFrame(() => {
          debugRoomOpenLogFn(phase, details);
        });
        return;
      }
      debugRoomOpenLogFn(phase, details);
    },
    addPerfPhaseFn,
    sortMessagesChronologicallyFn,
    syncConversationRoomSenderKeysFn,
    dmUnavailableError,
    retryFailedConversationMessagesFn,
    tryDecryptMessageFn,
    getMessageTimestampValueFn,
    createMessageSendActionFn,
    isE2EInitializedFn,
    hasKnownNpubFn,
    encryptGroupMessageFn,
    encryptDirectMessageFn,
    createConversationTimestampFn,
    appendOrReplaceMessageFn,
    updateCachedConversationStateFn,
    sanitizeCachedAttachmentsFn,
    persistDecryptedMessageFn,
    revokeAttachmentPreviewUrlsFn,
    createLoadMoreMessagesActionFn,
    prependOlderMessagesFn,
    createEditMessageActionFn,
    createDeleteMessageActionFn,
  };
}
