export function buildUseMessagesRuntimeContracts({
  clearAllMessageCachesFn = () => {},
  clearDecryptedMessageCachesFn = () => {},
  clearConversationCacheStateFn = () => {},
  clearMessageDecryptRuntimeFn = () => {},
  revokeAttachmentPreviewUrlsFn = () => {},
  resetMessageLaneStateFn = () => {},
  hydrateConversationStateFn = () => {},
  getConversationCacheKeyFn = () => '',
  getCachedConversationStateFn = () => null,
  bindDMDecryptRetryFn = () => {},
  bindRoomSenderKeyRetryFn = () => {},
  windowObj = null,
  schedulePendingDecryptExpiryFn = () => {},
  visibleTimeoutMs = 0,
  getPendingDecryptVisibilityDelayFn = () => 0,
  expirePendingDecryptMessagesFn = () => {},
  cacheConversationStateFn = () => {},
  shouldRetryFailedDMConversationMessagesFn = () => false,
  subscribeConversationRealtimeFn = () => {},
  buildConversationRealtimeOptionsFn = () => ({}),
  tryDecryptMessageFn = async () => null,
  appendOrReplaceMessageFn = () => [],
  updateCachedConversationStateFn = () => {},
  sanitizeCachedAttachmentsFn = (attachments) => attachments,
  persistDecryptedMessageFn = () => {},
  processIncomingConversationMessageFn = () => {},
  persistReadableConversationMessagesFn = () => {},
  subscribeConversationLifecycleFn = () => {},
  buildConversationLifecycleOptionsFn = () => ({}),
  deletePersistedMessageEntryFn = () => {},
  applyEditedConversationMessageFn = () => {},
  applyDeletedConversationMessageFn = () => {},
} = {}) {
  return {
    clearAllMessageCachesFn: () => clearAllMessageCachesFn({
      clearDecryptedMessageCachesFn,
      clearConversationCacheStateFn,
      clearMessageDecryptRuntimeFn,
      revokeAttachmentPreviewUrlsFn,
    }),
    revokeAttachmentPreviewUrlsFn,
    resetMessageLaneStateFn,
    hydrateConversationStateFn,
    getConversationCacheKeyFn,
    getCachedConversationStateFn,
    bindDMDecryptRetryFn,
    bindRoomSenderKeyRetryFn,
    windowObj,
    schedulePendingDecryptExpiryFn,
    visibleTimeoutMs,
    getPendingDecryptVisibilityDelayFn,
    expirePendingDecryptMessagesFn,
    cacheConversationStateFn,
    shouldRetryFailedDMConversationMessagesFn,
    subscribeConversationRealtimeFn,
    buildConversationRealtimeOptionsFn,
    tryDecryptMessageFn,
    appendOrReplaceMessageFn,
    updateCachedConversationStateFn,
    sanitizeCachedAttachmentsFn,
    persistDecryptedMessageFn,
    processIncomingConversationMessageFn,
    persistReadableConversationMessagesFn,
    subscribeConversationLifecycleFn,
    buildConversationLifecycleOptionsFn,
    deletePersistedMessageEntryFn,
    applyEditedConversationMessageFn,
    applyDeletedConversationMessageFn,
  };
}
