import { useVoiceHookRuntimeBindingsControllerRuntime } from './useVoiceHookRuntimeBindingsControllerRuntime.mjs';
import { buildUseVoiceHookRuntimeBindingsControllerOptions } from './voiceHookControllerBindings.mjs';
import { buildUseVoiceHookRuntimeBindingsControllerRuntimeValue } from './voiceHookControllerRuntimeBuilders.mjs';

export function useVoiceHookRuntimeEffectsController({
  state = {},
  refs = {},
  socket = null,
  currentUserId = null,
  rememberUsersFn,
  getUntrustedVoiceParticipantsFn,
  buildVoiceTrustErrorFn,
  setJoinErrorFn,
  setVoiceE2EFn,
  setE2EWarningFn,
  syncVoiceParticipantsFn,
  syncVoiceE2EStateFn,
  handleUnexpectedVoiceSessionEndFn,
  cleanupRemoteProducerFn,
  consumeProducerFn,
  isExpectedVoiceTeardownErrorFn,
  setPeersFn,
  resetVoiceSessionFn,
  updateVoiceDiagnosticsFn,
  prefersAppleSystemVoiceIsolationFn,
  electronAPI,
  summarizeProducerStatsFn,
  summarizeConsumerStatsFn,
  isVoiceDiagnosticsEnabledFn,
  getBitrateBpsFn,
  setScreenShareDiagnosticsFn,
  maybeAdaptScreenShareProfileFn,
  summarizeTrackSnapshotFn,
  summarizeScreenShareProfileFn,
  summarizeScreenShareHardwareFn,
  screenShareProfiles,
  roundRateFn,
  clearTimeoutFn,
} = {}) {
  useVoiceHookRuntimeBindingsControllerRuntime(buildUseVoiceHookRuntimeBindingsControllerOptions({
    state,
    refs,
    runtime: buildUseVoiceHookRuntimeBindingsControllerRuntimeValue({
      socket,
      currentUserId,
      rememberUsersFn,
      getUntrustedVoiceParticipantsFn,
      buildVoiceTrustErrorFn,
      setJoinErrorFn,
      setVoiceE2EFn,
      setE2EWarningFn,
      syncVoiceParticipantsFn,
      syncVoiceE2EStateFn,
      handleUnexpectedVoiceSessionEndFn,
      cleanupRemoteProducerFn,
      consumeProducerFn,
      isExpectedVoiceTeardownErrorFn,
      setPeersFn,
      resetVoiceSessionFn,
      updateVoiceDiagnosticsFn,
      prefersAppleSystemVoiceIsolationFn,
      electronAPI,
      summarizeProducerStatsFn,
      summarizeConsumerStatsFn,
      isVoiceDiagnosticsEnabledFn,
      getBitrateBpsFn,
      setScreenShareDiagnosticsFn,
      maybeAdaptScreenShareProfileFn,
      summarizeTrackSnapshotFn,
      summarizeScreenShareProfileFn,
      summarizeScreenShareHardwareFn,
      screenShareProfiles,
      roundRateFn,
      clearTimeoutFn,
    }),
  }));
}
