import { buildUseVoiceRuntimeEffectsOptions } from './voiceControllerBindings.mjs';

export function buildUseVoiceRuntimeEffectsContract({
  state = {},
  refs = {},
  runtime = {},
} = {}) {
  return buildUseVoiceRuntimeEffectsOptions({
    state: {
      voiceProcessingMode: state.voiceProcessingMode,
      channelId: state.channelId,
      muted: state.muted,
      deafened: state.deafened,
      screenShareDiagnostics: state.screenShareDiagnostics,
      screenSharing: state.screenSharing,
    },
    refs: {
      voiceProcessingModeRef: refs.voiceProcessingModeRef,
      channelIdRef: refs.channelIdRef,
      mutedRef: refs.mutedRef,
      deafenedRef: refs.deafenedRef,
      appleVoiceAvailableRef: refs.appleVoiceAvailableRef,
      producerUserMapRef: refs.producerUserMapRef,
      participantIdsRef: refs.participantIdsRef,
      producerRef: refs.producerRef,
      consumersRef: refs.consumersRef,
      producerMetaRef: refs.producerMetaRef,
      pendingLiveReconfigureRef: refs.pendingLiveReconfigureRef,
      screenShareProducerRef: refs.screenShareProducerRef,
      screenShareStreamRef: refs.screenShareStreamRef,
      screenShareStatsRef: refs.screenShareStatsRef,
      screenShareProfileIndexRef: refs.screenShareProfileIndexRef,
      screenShareSimulcastEnabledRef: refs.screenShareSimulcastEnabledRef,
      screenShareAdaptationRef: refs.screenShareAdaptationRef,
      leaveChannelRef: refs.leaveChannelRef,
    },
    runtime: {
      socket: runtime.socket,
      currentUserId: runtime.currentUserId,
      rememberUsersFn: runtime.rememberUsersFn,
      getUntrustedVoiceParticipantsFn: runtime.getUntrustedVoiceParticipantsFn,
      buildVoiceTrustErrorFn: runtime.buildVoiceTrustErrorFn,
      setJoinErrorFn: runtime.setJoinErrorFn,
      setVoiceE2EFn: runtime.setVoiceE2EFn,
      setE2EWarningFn: runtime.setE2EWarningFn,
      syncVoiceParticipantsFn: runtime.syncVoiceParticipantsFn,
      syncVoiceE2EStateFn: runtime.syncVoiceE2EStateFn,
      handleUnexpectedVoiceSessionEndFn: runtime.handleUnexpectedVoiceSessionEndFn,
      cleanupRemoteProducerFn: runtime.cleanupRemoteProducerFn,
      consumeProducerFn: runtime.consumeProducerFn,
      resumeVoiceMediaAfterKeyUpdateFn: runtime.resumeVoiceMediaAfterKeyUpdateFn,
      isExpectedVoiceTeardownErrorFn: runtime.isExpectedVoiceTeardownErrorFn,
      setPeersFn: runtime.setPeersFn,
      resetVoiceSessionFn: runtime.resetVoiceSessionFn,
      updateVoiceDiagnosticsFn: runtime.updateVoiceDiagnosticsFn,
      prefersAppleSystemVoiceIsolationFn: runtime.prefersAppleSystemVoiceIsolationFn,
      electronAPI: runtime.electronAPI,
      summarizeProducerStatsFn: runtime.summarizeProducerStatsFn,
      summarizeConsumerStatsFn: runtime.summarizeConsumerStatsFn,
      isVoiceDiagnosticsEnabledFn: runtime.isVoiceDiagnosticsEnabledFn,
      getBitrateBpsFn: runtime.getBitrateBpsFn,
      setScreenShareDiagnosticsFn: runtime.setScreenShareDiagnosticsFn,
      maybeAdaptScreenShareProfileFn: runtime.maybeAdaptScreenShareProfileFn,
      summarizeTrackSnapshotFn: runtime.summarizeTrackSnapshotFn,
      summarizeScreenShareProfileFn: runtime.summarizeScreenShareProfileFn,
      summarizeScreenShareHardwareFn: runtime.summarizeScreenShareHardwareFn,
      screenShareProfiles: runtime.screenShareProfiles,
      roundRateFn: runtime.roundRateFn,
      clearTimeoutFn: runtime.clearTimeoutFn,
    },
  });
}
