import { useVoiceSessionController } from './useVoiceSessionController.mjs';

export function useVoiceSessionActionController({
  socket = null,
  state = {},
  refs = {},
  runtime = {},
  constants = {},
  deps = [],
} = {}) {
  return useVoiceSessionController({
    socket,
    refs: {
      voiceHealthProbeRetryCountRef: refs.voiceHealthProbeRetryCountRef,
      pendingLiveReconfigureRef: refs.pendingLiveReconfigureRef,
      liveCaptureConfigGenRef: refs.liveCaptureConfigGenRef,
      vadIntervalRef: refs.vadIntervalRef,
      noiseSuppressorNodeRef: refs.noiseSuppressorNodeRef,
      residualDenoiserNodeRef: refs.residualDenoiserNodeRef,
      noiseGateNodeRef: refs.noiseGateNodeRef,
      speechFocusChainRef: refs.speechFocusChainRef,
      keyboardSuppressorNodeRef: refs.keyboardSuppressorNodeRef,
      noiseSuppressionRoutingRef: refs.noiseSuppressionRoutingRef,
      appleVoiceFrameCleanupRef: refs.appleVoiceFrameCleanupRef,
      appleVoiceStateCleanupRef: refs.appleVoiceStateCleanupRef,
      appleVoiceSourceNodeRef: refs.appleVoiceSourceNodeRef,
      micAudioCtxRef: refs.micAudioCtxRef,
      micGainNodeRef: refs.micGainNodeRef,
      localStreamRef: refs.localStreamRef,
      screenShareAudioProducerRef: refs.screenShareAudioProducerRef,
      screenShareProducerRef: refs.screenShareProducerRef,
      screenShareStreamRef: refs.screenShareStreamRef,
      screenShareStatsRef: refs.screenShareStatsRef,
      screenShareVideosRef: refs.screenShareVideosRef,
      producerRef: refs.producerRef,
      consumersRef: refs.consumersRef,
      producerUserMapRef: refs.producerUserMapRef,
      producerMetaRef: refs.producerMetaRef,
      audioElementsRef: refs.audioElementsRef,
      userAudioRef: refs.userAudioRef,
      sendTransportRef: refs.sendTransportRef,
      screenSendTransportRef: refs.screenSendTransportRef,
      recvTransportRef: refs.recvTransportRef,
      deviceRef: refs.deviceRef,
      liveCaptureRef: refs.liveCaptureRef,
      participantIdsRef: refs.participantIdsRef,
      channelIdRef: refs.channelIdRef,
      mutedBeforeDeafenRef: refs.mutedBeforeDeafenRef,
      joinGenRef: refs.joinGenRef,
      pendingSecureVoiceJoinRef: refs.pendingSecureVoiceJoinRef,
      pendingVoiceModeSwitchTraceRef: refs.pendingVoiceModeSwitchTraceRef,
    },
    setters: {
      setShowSourcePickerFn: state.setShowSourcePicker,
      setScreenSharingFn: state.setScreenSharing,
      setScreenShareStreamFn: state.setScreenShareStream,
      setScreenShareErrorFn: state.setScreenShareError,
      setScreenShareDiagnosticsFn: state.setScreenShareDiagnostics,
      setIncomingScreenSharesFn: state.setIncomingScreenShares,
      setChannelIdFn: state.setChannelId,
      setVoiceChannelIdFn: runtime.setVoiceChannelIdFn,
      setVoiceChannelParticipantsFn: runtime.setVoiceChannelParticipantsFn,
      setJoinErrorFn: state.setJoinError,
      setVoiceE2EFn: state.setVoiceE2E,
      setE2EWarningFn: state.setE2EWarning,
      setLiveVoiceFallbackReasonFn: state.setLiveVoiceFallbackReason,
      setMutedFn: state.setMuted,
      setDeafenedFn: state.setDeafened,
      setSpeakingFn: state.setSpeaking,
      setPeersFn: state.setPeers,
    },
    runtime,
    constants,
    deps,
  });
}
