import { buildUseVoiceHookSessionRuntime } from './voiceHookControllerRuntimeBindings.mjs';
import { buildUseVoiceHookSessionRuntimeDeps } from './voiceHookControllerRuntimeDeps.mjs';

export function buildUseVoiceHookSessionControllerRuntimeValue({
  emitAsyncFn,
  clearVoiceHealthProbeFn,
  stopAppleVoiceCaptureFn,
  resetScreenShareAdaptationFn,
  clearVoiceKeyFn,
  updateVoiceDiagnosticsFn,
  setVoiceChannelIdFn,
  setVoiceChannelParticipantsFn,
  joinGenRef,
  setTimeoutFn,
  playLeaveChimeFn,
  clearTimeoutFn,
  cancelPerfTraceFn,
  setJoinErrorFn,
  setE2EWarningFn,
  setLiveVoiceFallbackReasonFn,
  recordLaneDiagnosticFn,
  ensureSecureMediaReadyFn,
  rememberUsersFn,
  getUntrustedVoiceParticipantsFn,
  buildVoiceTrustErrorFn,
  deviceCtor,
  deviceRef,
  createSendTransportFn,
  createRecvTransportFn,
  setChannelIdFn,
  setDeafenedFn,
  syncVoiceParticipantsFn,
  getVoiceParticipantIdsFn,
  consumeProducerFn,
  syncVoiceE2EStateFn,
  playConnectChimeFn,
  getPlatformFn,
  prefetchDesktopSourcesFn,
  applyLiveCaptureToProducerFn,
  setMutedFn,
  scheduleVoiceHealthProbeFn,
  resumeVoiceMediaAfterKeyUpdateFn,
  getCurrentVoiceKeyFn,
  isExpectedVoiceTeardownErrorFn,
  normalizeVoiceErrorMessageFn,
  scheduleClearJoinErrorFn,
  logErrorFn,
  voiceSessionErrorTimeoutMs,
  appleVoiceCaptureOwner,
  resetControlState,
  deps = [],
} = {}) {
  return buildUseVoiceHookSessionRuntime(buildUseVoiceHookSessionRuntimeDeps({
    emitAsyncFn,
    clearVoiceHealthProbeFn,
    stopAppleVoiceCaptureFn,
    resetScreenShareAdaptationFn,
    clearVoiceKeyFn,
    updateVoiceDiagnosticsFn,
    setVoiceChannelIdFn,
    setVoiceChannelParticipantsFn,
    advanceJoinGenerationFn: () => {
      joinGenRef.current += 1;
    },
    setTimeoutFn,
    playLeaveChimeFn,
    clearTimeoutFn,
    cancelPerfTraceFn,
    setJoinErrorFn,
    setE2EWarningFn,
    setLiveVoiceFallbackReasonFn,
    recordLaneDiagnosticFn,
    ensureSecureMediaReadyFn,
    rememberUsersFn,
    getUntrustedVoiceParticipantsFn,
    buildVoiceTrustErrorFn,
    deviceCtor,
    setDeviceFn: (device) => {
      deviceRef.current = device;
    },
    createSendTransportFn,
    createRecvTransportFn,
    setChannelIdFn,
    setDeafenedFn,
    syncVoiceParticipantsFn,
    getVoiceParticipantIdsFn,
    consumeProducerFn,
    syncVoiceE2EStateFn,
    playConnectChimeFn,
    getPlatformFn,
    prefetchDesktopSourcesFn,
    applyLiveCaptureToProducerFn,
    setMutedFn,
    scheduleVoiceHealthProbeFn,
    resumeVoiceMediaAfterKeyUpdateFn,
    getCurrentVoiceKeyFn,
    isExpectedVoiceTeardownErrorFn,
    normalizeVoiceErrorMessageFn,
    scheduleClearJoinErrorFn,
    logErrorFn,
    constants: {
      voiceSessionErrorTimeoutMs,
      appleVoiceCaptureOwner,
      resetControlState,
    },
    deps,
  }));
}
