export function buildVoiceCaptureErrorResult({
  chId = null,
  captureStartedAt = null,
  activeVoiceProcessingMode = null,
  appliedConstraints = null,
  usedDefaultDeviceFallback = false,
  requestedSuppressionRuntime = null,
  noiseSuppressionEnabled = false,
  useRawMicPath = false,
  getUserMediaMs = null,
  totalMs = null,
  micErr = null,
  createVoiceFilterDiagnosticsFn,
  buildVoiceCaptureDiagnosticsFn,
} = {}) {
  return {
    capture: null,
    error: micErr,
    diagnostics: buildVoiceCaptureDiagnosticsFn({
      channelId: chId,
      startedAt: captureStartedAt,
      mode: activeVoiceProcessingMode,
      requestedConstraints: appliedConstraints?.audio,
      usedDefaultDeviceFallback,
      reusedSourceStream: false,
      filter: createVoiceFilterDiagnosticsFn({
        suppressionRuntime: requestedSuppressionRuntime,
        requestedSuppressionRuntime,
        noiseSuppressionEnabled,
        useRawMicPath,
      }),
      getUserMediaMs,
      totalMs,
      error: micErr?.message || 'Microphone unavailable',
    }),
  };
}

export function buildSafeModeVoiceCaptureResult({
  capture,
  chId = null,
  captureStartedAt = null,
  activeVoiceProcessingMode = null,
  appliedConstraints = null,
  usedDefaultDeviceFallback = false,
  reusedExistingStream = false,
  sourceTrack = null,
  getUserMediaMs = null,
  audioGraphSetupMs = null,
  totalMs = null,
  filterDiagnostics = {},
  summarizeTrackSnapshotFn = (value) => value,
  summarizeAudioContextFn = (value) => value,
  buildVoiceCaptureDiagnosticsFn,
} = {}) {
  return {
    capture,
    diagnostics: buildVoiceCaptureDiagnosticsFn({
      channelId: chId,
      startedAt: captureStartedAt,
      mode: activeVoiceProcessingMode,
      requestedConstraints: appliedConstraints?.audio,
      usedDefaultDeviceFallback,
      reusedSourceStream: reusedExistingStream,
      sourceTrack: summarizeTrackSnapshotFn(sourceTrack),
      producedTrack: summarizeTrackSnapshotFn(capture?.outputTrack),
      outputTrackMode: capture?.outputTrackMode || null,
      audioContext: summarizeAudioContextFn(capture?.micCtx),
      filter: {
        ...filterDiagnostics,
        backend: 'raw',
        loaded: true,
        requiresWarmup: false,
        fallbackReason: 'Voice safe mode active',
        workletCreateMs: null,
      },
      getUserMediaMs,
      audioGraphSetupMs,
      totalMs,
    }),
    noiseSuppressionEnabled: false,
  };
}

export function buildProcessedVoiceCaptureResult({
  capture,
  chId = null,
  captureStartedAt = null,
  activeVoiceProcessingMode = null,
  appliedConstraints = null,
  usedDefaultDeviceFallback = false,
  reusedExistingStream = false,
  sourceTrack = null,
  micCtx = null,
  filterDiagnostics = {},
  workletCreateMs = null,
  getUserMediaMs = null,
  audioGraphSetupMs = null,
  totalMs = null,
  noiseSuppressionEnabled = false,
  summarizeTrackSnapshotFn = (value) => value,
  summarizeAudioContextFn = (value) => value,
  buildVoiceCaptureDiagnosticsFn,
} = {}) {
  return {
    capture,
    diagnostics: buildVoiceCaptureDiagnosticsFn({
      channelId: chId,
      startedAt: captureStartedAt,
      mode: activeVoiceProcessingMode,
      requestedConstraints: appliedConstraints?.audio,
      usedDefaultDeviceFallback,
      reusedSourceStream: reusedExistingStream,
      sourceTrack: summarizeTrackSnapshotFn(sourceTrack),
      producedTrack: summarizeTrackSnapshotFn(capture?.outputTrack),
      outputTrackMode: capture?.outputTrackMode || null,
      audioContext: summarizeAudioContextFn(micCtx),
      filter: {
        ...filterDiagnostics,
        workletCreateMs,
      },
      getUserMediaMs,
      audioGraphSetupMs,
      totalMs,
    }),
    noiseSuppressionEnabled,
  };
}
