export function buildVoiceSessionActionControllerOptions({
  socket = null,
  state = {},
  refs = {},
  runtime = {},
  constants = {},
  deps = [],
} = {}) {
  return {
    socket,
    state,
    refs,
    runtime,
    constants,
    deps,
  };
}

export function buildVoiceSessionActionRuntime({
  emitAsyncFn = async () => null,
  clearVoiceHealthProbeFn = () => {},
  stopAppleVoiceCaptureFn = () => {},
  resetScreenShareAdaptationFn = () => {},
  clearVoiceKeyFn = () => {},
  updateVoiceDiagnosticsFn = () => {},
  setVoiceChannelIdFn = () => {},
  setVoiceChannelParticipantsFn = () => {},
  advanceJoinGenerationFn = () => {},
  setTimeoutFn = () => {},
  playLeaveChimeFn = () => {},
  clearTimeoutFn = () => {},
  cancelPerfTraceFn = () => {},
  joinRuntime = {},
} = {}) {
  return {
    emitAsyncFn,
    clearVoiceHealthProbeFn,
    stopAppleVoiceCaptureFn,
    resetScreenShareAdaptationFn,
    clearVoiceKeyFn,
    updateVoiceDiagnosticsFn,
    setVoiceChannelIdFn,
    setVoiceChannelParticipantsFn,
    advanceJoinGenerationFn,
    setTimeoutFn,
    playLeaveChimeFn,
    clearTimeoutFn,
    cancelPerfTraceFn,
    joinRuntime,
  };
}

export function buildVoiceSessionJoinRuntime({
  setJoinErrorFn = () => {},
  setE2EWarningFn = () => {},
  setLiveVoiceFallbackReasonFn = () => {},
  recordLaneDiagnosticFn = () => {},
  ensureSecureMediaReadyFn = async () => true,
  emitAsyncFn = async () => null,
  rememberUsersFn = () => {},
  getUntrustedVoiceParticipantsFn = () => [],
  buildVoiceTrustErrorFn = () => null,
  deviceCtor = null,
  setDeviceFn = () => {},
  createSendTransportFn = async () => null,
  createRecvTransportFn = async () => null,
  setChannelIdFn = () => {},
  setDeafenedFn = () => {},
  setVoiceChannelIdFn = () => {},
  syncVoiceParticipantsFn = () => {},
  getVoiceParticipantIdsFn = () => [],
  updateVoiceDiagnosticsFn = () => {},
  consumeProducerFn = async () => null,
  syncVoiceE2EStateFn = () => {},
  playConnectChimeFn = () => {},
  getPlatformFn = () => null,
  prefetchDesktopSourcesFn = () => {},
  applyLiveCaptureToProducerFn = async () => null,
  setMutedFn = () => {},
  clearVoiceHealthProbeFn = () => {},
  scheduleVoiceHealthProbeFn = () => {},
  resumeVoiceMediaAfterKeyUpdateFn = async () => ({ resumed: false }),
  getCurrentVoiceKeyFn = () => null,
  isExpectedVoiceTeardownErrorFn = () => false,
  normalizeVoiceErrorMessageFn = (value) => value,
  scheduleClearJoinErrorFn = () => {},
  logErrorFn = () => {},
} = {}) {
  return {
    setJoinErrorFn,
    setE2EWarningFn,
    setLiveVoiceFallbackReasonFn,
    recordLaneDiagnosticFn,
    ensureSecureMediaReadyFn,
    emitAsyncFn,
    rememberUsersFn,
    getUntrustedVoiceParticipantsFn,
    buildVoiceTrustErrorFn,
    deviceCtor,
    setDeviceFn,
    createSendTransportFn,
    createRecvTransportFn,
    setChannelIdFn,
    setDeafenedFn,
    setVoiceChannelIdFn,
    syncVoiceParticipantsFn,
    getVoiceParticipantIdsFn,
    updateVoiceDiagnosticsFn,
    consumeProducerFn,
    syncVoiceE2EStateFn,
    playConnectChimeFn,
    getPlatformFn,
    prefetchDesktopSourcesFn,
    applyLiveCaptureToProducerFn,
    setMutedFn,
    clearVoiceHealthProbeFn,
    scheduleVoiceHealthProbeFn,
    resumeVoiceMediaAfterKeyUpdateFn,
    getCurrentVoiceKeyFn,
    isExpectedVoiceTeardownErrorFn,
    normalizeVoiceErrorMessageFn,
    scheduleClearJoinErrorFn,
    logErrorFn,
  };
}
