export function buildUseVoiceHookActionSessionCoreRuntimeOptions({
  socket = null,
  emitAsyncFn,
  updateVoiceDiagnosticsFn,
  coreRuntime = {},
} = {}) {
  const {
    resetScreenShareAdaptation,
    ensureSecureMediaReady,
    syncVoiceE2EState,
    getUntrustedVoiceParticipants,
    buildVoiceTrustError,
    syncVoiceParticipants,
    clearVoiceHealthProbe,
    scheduleVoiceHealthProbe,
    createSendTransport,
    createRecvTransport,
    consumeProducer,
    applyLiveCaptureToProducer,
    resumeVoiceMediaAfterKeyUpdate,
    getCurrentVoiceKey,
  } = coreRuntime;

  return {
    clearVoiceHealthProbeFn: clearVoiceHealthProbe,
    resetScreenShareAdaptationFn: resetScreenShareAdaptation,
    ensureSecureMediaReadyFn: ensureSecureMediaReady,
    getUntrustedVoiceParticipantsFn: getUntrustedVoiceParticipants,
    buildVoiceTrustErrorFn: buildVoiceTrustError,
    syncVoiceParticipantsFn: syncVoiceParticipants,
    createSendTransportFn: async (nextChannelId) => createSendTransport(nextChannelId),
    createRecvTransportFn: async (nextChannelId) => createRecvTransport(nextChannelId),
    consumeProducerFn: consumeProducer,
    syncVoiceE2EStateFn: syncVoiceE2EState,
    applyLiveCaptureToProducerFn: applyLiveCaptureToProducer,
    scheduleVoiceHealthProbeFn: scheduleVoiceHealthProbe,
    resumeVoiceMediaAfterKeyUpdateFn: resumeVoiceMediaAfterKeyUpdate,
    getCurrentVoiceKeyFn: getCurrentVoiceKey,
    deps: [
      applyLiveCaptureToProducer,
      buildVoiceTrustError,
      clearVoiceHealthProbe,
      consumeProducer,
      createRecvTransport,
      createSendTransport,
      emitAsyncFn,
      ensureSecureMediaReady,
      getCurrentVoiceKey,
      getUntrustedVoiceParticipants,
      resumeVoiceMediaAfterKeyUpdate,
      scheduleVoiceHealthProbe,
      socket,
      syncVoiceE2EState,
      syncVoiceParticipants,
      updateVoiceDiagnosticsFn,
    ],
  };
}
