export function buildUseVoiceHookActionRuntimeEffectsOptions({
  state = {},
  refs = {},
  socket = null,
  currentUserId = null,
  rememberUsersFn,
  getUntrustedVoiceParticipantsFn,
  buildVoiceTrustErrorFn,
  setJoinErrorFn,
  setVoiceE2EFn,
  setE2EWarningFn,
  syncVoiceParticipantsFn,
  syncVoiceE2EStateFn,
  handleUnexpectedVoiceSessionEndFn,
  cleanupRemoteProducerFn,
  consumeProducerFn,
  isExpectedVoiceTeardownErrorFn,
  setPeersFn,
  resetVoiceSessionFn,
  updateVoiceDiagnosticsFn,
  prefersAppleSystemVoiceIsolationFn,
  electronAPI,
  summarizeProducerStatsFn,
  summarizeConsumerStatsFn,
  isVoiceDiagnosticsEnabledFn,
  getBitrateBpsFn,
  setScreenShareDiagnosticsFn,
  maybeAdaptScreenShareProfileFn,
  summarizeTrackSnapshotFn,
  summarizeScreenShareProfileFn,
  summarizeScreenShareHardwareFn,
  screenShareProfiles,
  roundRateFn,
  clearTimeoutFn,
} = {}) {
  return {
    state,
    refs,
    socket,
    currentUserId,
    rememberUsersFn,
    getUntrustedVoiceParticipantsFn,
    buildVoiceTrustErrorFn,
    setJoinErrorFn,
    setVoiceE2EFn,
    setE2EWarningFn,
    syncVoiceParticipantsFn,
    syncVoiceE2EStateFn,
    handleUnexpectedVoiceSessionEndFn,
    cleanupRemoteProducerFn,
    consumeProducerFn,
    isExpectedVoiceTeardownErrorFn,
    setPeersFn,
    resetVoiceSessionFn,
    updateVoiceDiagnosticsFn,
    prefersAppleSystemVoiceIsolationFn,
    electronAPI,
    summarizeProducerStatsFn,
    summarizeConsumerStatsFn,
    isVoiceDiagnosticsEnabledFn,
    getBitrateBpsFn,
    setScreenShareDiagnosticsFn,
    maybeAdaptScreenShareProfileFn,
    summarizeTrackSnapshotFn,
    summarizeScreenShareProfileFn,
    summarizeScreenShareHardwareFn,
    screenShareProfiles,
    roundRateFn,
    clearTimeoutFn,
  };
}
