export function buildUseVoiceHookUiRuntimeDeps({
  clearVoiceHealthProbeFn,
  scheduleVoiceHealthProbeFn,
  scheduleVoiceLiveReconfigureFlowFn,
  clearTimeoutFn,
  setTimeoutFn,
  cancelPerfTraceFn,
  addPerfPhaseFn,
  reconfigureLiveCaptureFn,
  startPerfTraceFn,
  endPerfTraceFn,
  switchLiveCaptureModeInPlaceFn,
  applyNoiseSuppressionRoutingFn,
  applyVoiceModeDependenciesFn,
  persistVoiceProcessingModeFn,
  persistNoiseSuppressionEnabledFn,
  isUltraLowLatencyModeFn,
  deps = [],
} = {}) {
  return {
    clearVoiceHealthProbeFn,
    scheduleVoiceHealthProbeFn,
    scheduleVoiceLiveReconfigureFlowFn,
    clearTimeoutFn,
    setTimeoutFn,
    cancelPerfTraceFn,
    addPerfPhaseFn,
    reconfigureLiveCaptureFn,
    startPerfTraceFn,
    endPerfTraceFn,
    switchLiveCaptureModeInPlaceFn,
    applyNoiseSuppressionRoutingFn,
    applyVoiceModeDependenciesFn,
    persistVoiceProcessingModeFn,
    persistNoiseSuppressionEnabledFn,
    isUltraLowLatencyModeFn,
    deps,
  };
}
