export function buildMainLayoutViewStateOptions({
  e2eWarning = false,
  versionToast = null,
  showUpdateOverlay = false,
  latestVersionInfo = null,
  headerState = null,
  updateButtonState = null,
  handleUpdateButtonClick = async () => {},
  windowObj = null,
  showPiP = false,
  conversation = null,
  handleSelectStream = () => {},
  setShowPiP = () => {},
  rooms = [],
  myRooms = [],
  createRoom = () => {},
  joinRoom = () => {},
  renameRoom = () => {},
  deleteRoom = () => {},
  handleSelectRoom = () => {},
  handleSelectDM = () => {},
  handleSelectAssetDump = () => {},
  handleSelectAddons = () => {},
  handleSelectNostrProfile = () => {},
  handleSelectVoiceChannel = () => {},
  handleSelectGuildChatHome = () => {},
  handleSelectGuildChatFull = () => {},
  handleCollapseGuildChatFull = () => {},
  guildChatHasUnreadMention = false,
  unreadCounts = {},
  unreadRoomCounts = {},
  conversationOpenTraceId = null,
  setGuildChatCompact = () => {},
  streamImmersive = false,
  setStreamImmersive = () => {},
  guildChatDockState = null,
  currentGuild = null,
  guildChat = null,
  guildChatAvailable = false,
  guildChatCompact = false,
  guildChatExpanded = false,
  showVerifyIdentity = false,
  conversationName = '',
  setVersionToast = () => {},
  setShowUpdateOverlay = () => {},
  setShowVerifyIdentity = () => {},
  insecureConnection = false,
  serverUrl = '',
} = {}) {
  return {
    insecureConnection,
    e2eWarning,
    versionToast,
    showUpdateOverlay,
    latestVersionInfo,
    serverUrl,
    setVersionToastFn: setVersionToast,
    setShowUpdateOverlayFn: setShowUpdateOverlay,
    headerState,
    updateButtonState,
    setShowVerifyIdentityFn: setShowVerifyIdentity,
    handleUpdateButtonClickFn: handleUpdateButtonClick,
    windowObj,
    showPiP,
    conversationType: conversation?.type || null,
    handleSelectStreamFn: handleSelectStream,
    setShowPiPFn: setShowPiP,
    rooms,
    myRooms,
    createRoomFn: createRoom,
    joinRoomFn: joinRoom,
    renameRoomFn: renameRoom,
    deleteRoomFn: deleteRoom,
    conversation,
    handleSelectRoomFn: handleSelectRoom,
    handleSelectDMFn: handleSelectDM,
    handleSelectAssetDumpFn: handleSelectAssetDump,
    handleSelectAddonsFn: handleSelectAddons,
    handleSelectNostrProfileFn: handleSelectNostrProfile,
    handleSelectVoiceChannelFn: handleSelectVoiceChannel,
    handleSelectGuildChatHomeFn: handleSelectGuildChatHome,
    handleSelectGuildChatFullFn: handleSelectGuildChatFull,
    handleCollapseGuildChatFullFn: handleCollapseGuildChatFull,
    guildChatHasUnreadMention,
    unreadCounts,
    unreadRoomCounts,
    conversationOpenTraceId,
    setGuildChatCompactFn: setGuildChatCompact,
    streamImmersive,
    setStreamImmersiveFn: setStreamImmersive,
    guildChatDockState,
    currentGuild,
    guildChat,
    guildChatAvailable,
    guildChatCompact,
    guildChatExpanded,
    showVerifyIdentity,
    conversationId: conversation?.id || null,
    conversationName,
  };
}
