export function buildMainLayoutControllerRuntimeOptions({
  socket = null,
  user = null,
  clearUnreadFn = () => {},
  clearUnreadRoomFn = () => {},
  clearGuildChatUnreadMentionsFn = () => {},
  conversationOpenTraceRef = null,
  setConversationFn = () => {},
  setConversationNameFn = () => {},
  setConversationOpenTraceIdFn = () => {},
  setLatestVersionInfoFn = () => {},
  setUpdateAvailableFn = () => {},
  setShowUpdateOverlayFn = () => {},
  setVersionToastFn = () => {},
  setGuildChatExpandedFn = () => {},
  updateState = {},
} = {}) {
  return {
    socket,
    user,
    clearUnreadFn,
    clearUnreadRoomFn,
    clearGuildChatUnreadMentionsFn,
    conversationOpenTraceRef,
    setConversationFn,
    setConversationNameFn,
    setConversationOpenTraceIdFn,
    setLatestVersionInfoFn,
    setUpdateAvailableFn,
    setShowUpdateOverlayFn,
    setVersionToastFn,
    setGuildChatExpandedFn,
    updateState,
  };
}

export function buildMainLayoutConversationEffectsOptions({
  screenSharing = {},
  conversation = null,
  conversationName = '',
  userId = null,
  username = '',
  channelId = null,
  activeVoiceChannel = null,
  activeRemoteStreamer = null,
  streamConversationMatchesActiveVoice = false,
  voiceChannels = [],
  socket = null,
  setConversationFn = () => {},
  setConversationNameFn = () => {},
  clearConversationFn = () => {},
  clearConversationPerfTraceFn = () => {},
  prevConversationRef = null,
  prevConversationNameRef = null,
  prevConversationTypeRef = null,
  prevJoinedVoiceChannelIdRef = null,
  setShowPiPFn = () => {},
} = {}) {
  return {
    screenSharing,
    conversation,
    conversationName,
    userId,
    username,
    channelId,
    activeVoiceChannel,
    activeRemoteStreamer,
    streamConversationMatchesActiveVoice,
    voiceChannels,
    socket,
    setConversationFn,
    setConversationNameFn,
    clearConversationFn,
    clearConversationPerfTraceFn,
    prevConversationRef,
    prevConversationNameRef,
    prevConversationTypeRef,
    prevJoinedVoiceChannelIdRef,
    setShowPiPFn,
  };
}

export function buildMainLayoutShellEffectsOptions({
  e2eWarning = false,
  setE2eWarningFn = () => {},
  refreshLatestVersionInfoFn = () => {},
  setAppVersionFn = () => {},
  socket = null,
  myRooms = [],
  rooms = [],
  conversation = null,
  clearConversationPerfTraceFn = () => {},
  clearGuildChatUnreadMentionsFn = () => {},
  handleSelectDM = () => {},
  handleSelectRoom = () => {},
  setConversationStateFn = () => {},
  guildChatInitialFocusAppliedRef = null,
  currentGuildData = null,
  showGuildChatDock = false,
  focusGuildChatComposerFn = () => {},
  streamImmersive = false,
  setStreamImmersiveFn = () => {},
  guildChatAvailable = false,
  guildChatExpanded = false,
  setGuildChatExpandedFn = () => {},
  setGuildChatCompactFn = () => {},
} = {}) {
  return {
    e2eWarning,
    setE2eWarningFn,
    refreshLatestVersionInfoFn,
    setAppVersionFn,
    socket,
    myRooms,
    rooms,
    conversation,
    clearConversationPerfTraceFn,
    clearGuildChatUnreadMentionsFn,
    handleSelectDM,
    handleSelectRoom,
    setConversationStateFn,
    guildChatInitialFocusAppliedRef,
    currentGuildData,
    showGuildChatDock,
    focusGuildChatComposerFn,
    streamImmersive,
    setStreamImmersiveFn,
    guildChatAvailable,
    guildChatExpanded,
    setGuildChatExpandedFn,
    setGuildChatCompactFn,
  };
}
