export function buildMainLayoutDerivedVoiceInput({
  screenSharing = {},
  peers = {},
  channelId = null,
  voiceChannels = [],
  conversation = null,
  currentUserId = null,
} = {}) {
  return {
    screenSharing,
    peers,
    channelId,
    voiceChannels,
    conversation,
    currentUserId,
  };
}

export function buildMainLayoutDerivedShellInput({
  currentGuild = null,
  currentGuildData = null,
  conversation = null,
  conversationName = '',
  isOnline = false,
  e2eReady = false,
  screenSharing = {},
  currentUserId = null,
  channelId = null,
  voiceChannels = [],
  guildChatCompact = false,
  guildChatExpanded = false,
  streamImmersive = false,
  updateAvailable = false,
  appVersion = '',
} = {}) {
  return {
    currentGuild,
    currentGuildName: currentGuildData?.name || '',
    conversation,
    conversationName,
    isOnline,
    e2eReady,
    screenSharing,
    currentUserId,
    channelId,
    voiceChannels,
    guildChatCompact,
    guildChatExpanded,
    streamImmersive,
    updateAvailable,
    appVersion,
  };
}

export function buildMainLayoutControllerRuntimeInput({
  socket = null,
  user = null,
  clearUnreadFn = () => {},
  clearUnreadRoomFn = () => {},
  clearGuildChatUnreadMentionsFn = () => {},
  conversationOpenTraceRef = null,
  setConversationFn = () => {},
  setConversationNameFn = () => {},
  setConversationOpenTraceIdFn = () => {},
  setLatestVersionInfoFn = () => {},
  setUpdateAvailableFn = () => {},
  setShowUpdateOverlayFn = () => {},
  setVersionToastFn = () => {},
  setGuildChatExpandedFn = () => {},
  conversation = null,
  conversationName = '',
  latestVersionInfo = null,
  updateAvailable = false,
  appVersion = '',
} = {}) {
  return {
    socket,
    user,
    clearUnreadFn,
    clearUnreadRoomFn,
    clearGuildChatUnreadMentionsFn,
    conversationOpenTraceRef,
    setConversationFn,
    setConversationNameFn,
    setConversationOpenTraceIdFn,
    setLatestVersionInfoFn,
    setUpdateAvailableFn,
    setShowUpdateOverlayFn,
    setVersionToastFn,
    setGuildChatExpandedFn,
    updateState: {
      getConversation: () => conversation,
      getConversationName: () => conversationName,
      getLatestVersionInfo: () => latestVersionInfo,
      getUpdateAvailable: () => updateAvailable,
      getAppVersion: () => appVersion,
    },
  };
}

export function buildMainLayoutConversationEffectsInput({
  screenSharing = {},
  conversation = null,
  conversationName = '',
  user = null,
  channelId = null,
  activeVoiceChannel = null,
  activeRemoteStreamer = null,
  streamConversationMatchesActiveVoice = false,
  voiceChannels = [],
  socket = null,
  setConversationFn = () => {},
  setConversationNameFn = () => {},
  clearConversationFn = () => {},
  clearConversationPerfTraceFn = () => {},
  prevConversationRef = null,
  prevConversationNameRef = null,
  prevConversationTypeRef = null,
  prevJoinedVoiceChannelIdRef = null,
  setShowPiPFn = () => {},
} = {}) {
  return {
    screenSharing,
    conversation,
    conversationName,
    userId: user?.userId,
    username: user?.username,
    channelId,
    activeVoiceChannel,
    activeRemoteStreamer,
    streamConversationMatchesActiveVoice,
    voiceChannels,
    socket,
    setConversationFn,
    setConversationNameFn,
    clearConversationFn,
    clearConversationPerfTraceFn,
    prevConversationRef,
    prevConversationNameRef,
    prevConversationTypeRef,
    prevJoinedVoiceChannelIdRef,
    setShowPiPFn,
  };
}

export function buildMainLayoutShellEffectsInput({
  e2eWarning = false,
  setE2eWarningFn = () => {},
  refreshLatestVersionInfoFn = () => {},
  setAppVersionFn = () => {},
  socket = null,
  myRooms = [],
  rooms = [],
  conversation = null,
  clearConversationPerfTraceFn = () => {},
  clearGuildChatUnreadMentionsFn = () => {},
  handleSelectDM = () => {},
  handleSelectRoom = () => {},
  setConversationStateFn = () => {},
  guildChatInitialFocusAppliedRef = null,
  currentGuildData = null,
  showGuildChatDock = false,
  focusGuildChatComposerFn = () => {},
  streamImmersive = false,
  setStreamImmersiveFn = () => {},
  guildChatAvailable = false,
  guildChatExpanded = false,
  setGuildChatExpandedFn = () => {},
  setGuildChatCompactFn = () => {},
} = {}) {
  return {
    e2eWarning,
    setE2eWarningFn,
    refreshLatestVersionInfoFn,
    setAppVersionFn,
    socket,
    myRooms,
    rooms,
    conversation,
    clearConversationPerfTraceFn,
    clearGuildChatUnreadMentionsFn,
    handleSelectDM,
    handleSelectRoom,
    setConversationStateFn,
    guildChatInitialFocusAppliedRef,
    currentGuildData,
    showGuildChatDock,
    focusGuildChatComposerFn,
    streamImmersive,
    setStreamImmersiveFn,
    guildChatAvailable,
    guildChatExpanded,
    setGuildChatExpandedFn,
    setGuildChatCompactFn,
  };
}

export function buildMainLayoutViewInput({
  e2eWarning = false,
  versionToast = null,
  showUpdateOverlay = false,
  latestVersionInfo = null,
  headerState = null,
  updateButtonState = null,
  handleUpdateButtonClick = async () => {},
  windowObj = null,
  showPiP = false,
  conversation = null,
  handleSelectStream = () => {},
  setShowPiP = () => {},
  rooms = [],
  myRooms = [],
  createRoom = () => {},
  joinRoom = () => {},
  renameRoom = () => {},
  deleteRoom = () => {},
  handleSelectRoom = () => {},
  handleSelectDM = () => {},
  handleSelectAssetDump = () => {},
  handleSelectAddons = () => {},
  handleSelectNostrProfile = () => {},
  handleSelectVoiceChannel = () => {},
  handleSelectGuildChatHome = () => {},
  handleSelectGuildChatFull = () => {},
  handleCollapseGuildChatFull = () => {},
  unreadCounts = {},
  unreadRoomCounts = {},
  conversationOpenTraceId = null,
  setGuildChatCompact = () => {},
  streamImmersive = false,
  setStreamImmersive = () => {},
  guildChatDockState = null,
  currentGuild = null,
  guildChat = null,
  guildChatAvailable = false,
  guildChatCompact = false,
  guildChatExpanded = false,
  showVerifyIdentity = false,
  conversationName = '',
  setVersionToast = () => {},
  setShowUpdateOverlay = () => {},
  setShowVerifyIdentity = () => {},
  insecureConnection = false,
  serverUrl = '',
} = {}) {
  return {
    insecureConnection,
    e2eWarning,
    versionToast,
    showUpdateOverlay,
    latestVersionInfo,
    serverUrl,
    headerState,
    updateButtonState,
    handleUpdateButtonClick,
    windowObj,
    showPiP,
    conversation,
    handleSelectStream,
    setShowPiP,
    rooms,
    myRooms,
    createRoom,
    joinRoom,
    renameRoom,
    deleteRoom,
    handleSelectRoom,
    handleSelectDM,
    handleSelectAssetDump,
    handleSelectAddons,
    handleSelectNostrProfile,
    handleSelectVoiceChannel,
    handleSelectGuildChatHome,
    handleSelectGuildChatFull,
    handleCollapseGuildChatFull,
    guildChatHasUnreadMention: guildChat?.hasUnreadMention || false,
    unreadCounts,
    unreadRoomCounts,
    conversationOpenTraceId,
    setGuildChatCompact,
    streamImmersive,
    setStreamImmersive,
    guildChatDockState,
    currentGuild,
    guildChat,
    guildChatAvailable,
    guildChatCompact,
    guildChatExpanded,
    showVerifyIdentity,
    conversationName,
    setVersionToast,
    setShowUpdateOverlay,
    setShowVerifyIdentity,
  };
}
