import {
  buildMainLayoutControllerRuntimeOptions,
} from './mainLayoutControllerBindings.mjs';
import {
  buildMainLayoutControllerRuntimeInput,
} from './mainLayoutControllerInputs.mjs';
import { useMainLayoutControllerEffects } from './useMainLayoutControllerEffects.mjs';
import { useMainLayoutControllerRuntime } from './useMainLayoutControllerRuntime.mjs';
import { useMainLayoutControllerViewState } from './useMainLayoutControllerViewState.mjs';

export function useMainLayoutControllerRuntimeView({
  socket = null,
  currentGuild = null,
  currentGuildData = null,
  user = null,
  screenSharing = {},
  voiceChannels = [],
  channelId = null,
  state = {},
  derived = {},
  support = {},
} = {}) {
  const {
    conversation = null,
    setConversation = () => {},
    conversationName = '',
    setConversationName = () => {},
    conversationOpenTraceId = null,
    setConversationOpenTraceId = () => {},
    updateAvailable = false,
    setUpdateAvailable = () => {},
    latestVersionInfo = null,
    setLatestVersionInfo = () => {},
    appVersion = '',
    setAppVersion = () => {},
    showUpdateOverlay = false,
    setShowUpdateOverlay = () => {},
    versionToast = '',
    setVersionToast = () => {},
    showPiP = false,
    setShowPiP = () => {},
    e2eWarning = false,
    setE2eWarning = () => {},
    showVerifyIdentity = false,
    setShowVerifyIdentity = () => {},
    guildChatCompact = false,
    setGuildChatCompact = () => {},
    guildChatExpanded = false,
    setGuildChatExpanded = () => {},
    streamImmersive = false,
    setStreamImmersive = () => {},
    guildChatInitialFocusAppliedRef = null,
    prevConversationRef = null,
    prevConversationNameRef = null,
    prevJoinedVoiceChannelIdRef = null,
    prevConvTypeRef = null,
    conversationOpenTraceRef = null,
  } = state;
  const {
    activeVoiceChannel = null,
    activeRemoteStreamer = null,
    streamConversationMatchesActiveVoice = false,
    guildChatAvailable = false,
    showGuildChatDock = false,
    guildChatDockState = {},
    headerState = {},
    updateButtonState = {},
  } = derived;
  const {
    rooms = [],
    myRooms = [],
    createRoom = () => {},
    joinRoom = () => {},
    renameRoom = () => {},
    deleteRoom = () => {},
    unreadCounts = {},
    clearUnread = () => {},
    unreadRoomCounts = {},
    clearUnreadRoom = () => {},
    guildChat = {},
    clearGuildChatUnreadMentions = () => {},
  } = support;

  const {
    refreshLatestVersionInfo,
    setConversationState,
    clearConversationPerfTrace,
    focusGuildChatComposer,
    handleUpdateButtonClick,
    handleSelectRoom,
    handleSelectDM,
    handleSelectAssetDump,
    handleSelectAddons,
    handleSelectStream,
    handleSelectNostrProfile,
    handleSelectVoiceChannel,
    handleSelectGuildChatHome,
    handleSelectGuildChatFull,
    handleCollapseGuildChatFull,
  } = useMainLayoutControllerRuntime(buildMainLayoutControllerRuntimeOptions(
    buildMainLayoutControllerRuntimeInput({
      socket,
      user,
      clearUnreadFn: clearUnread,
      clearUnreadRoomFn: clearUnreadRoom,
      clearGuildChatUnreadMentionsFn: clearGuildChatUnreadMentions,
      conversationOpenTraceRef,
      setConversationFn: setConversation,
      setConversationNameFn: setConversationName,
      setConversationOpenTraceIdFn: setConversationOpenTraceId,
      setLatestVersionInfoFn: setLatestVersionInfo,
      setUpdateAvailableFn: setUpdateAvailable,
      setShowUpdateOverlayFn: setShowUpdateOverlay,
      setVersionToastFn: setVersionToast,
      setGuildChatExpandedFn: setGuildChatExpanded,
      conversation,
      conversationName,
      latestVersionInfo,
      updateAvailable,
      appVersion,
    })
  ));

  useMainLayoutControllerEffects({
    screenSharing,
    conversation,
    conversationName,
    user,
    channelId,
    activeVoiceChannel,
    activeRemoteStreamer,
    streamConversationMatchesActiveVoice,
    voiceChannels,
    socket,
    setConversationFn: setConversation,
    setConversationNameFn: setConversationName,
    clearConversationPerfTraceFn: clearConversationPerfTrace,
    prevConversationRef,
    prevConversationNameRef,
    prevConversationTypeRef: prevConvTypeRef,
    prevJoinedVoiceChannelIdRef,
    setShowPiPFn: setShowPiP,
    e2eWarning,
    setE2eWarningFn: setE2eWarning,
    refreshLatestVersionInfoFn: refreshLatestVersionInfo,
    setAppVersionFn: setAppVersion,
    myRooms,
    rooms,
    clearGuildChatUnreadMentionsFn: clearGuildChatUnreadMentions,
    handleSelectDM,
    handleSelectRoom,
    setConversationStateFn: setConversationState,
    guildChatInitialFocusAppliedRef,
    currentGuildData,
    showGuildChatDock,
    focusGuildChatComposerFn: focusGuildChatComposer,
    streamImmersive,
    setStreamImmersiveFn: setStreamImmersive,
    guildChatAvailable,
    guildChatExpanded,
    setGuildChatExpandedFn: setGuildChatExpanded,
    setGuildChatCompactFn: setGuildChatCompact,
  });

  return useMainLayoutControllerViewState({
    e2eWarning,
    versionToast,
    showUpdateOverlay,
    latestVersionInfo,
    headerState,
    updateButtonState,
    handleUpdateButtonClick,
    showPiP,
    conversation,
    handleSelectStream,
    setShowPiP,
    rooms,
    myRooms,
    createRoom,
    joinRoom,
    renameRoom,
    deleteRoom,
    handleSelectRoom,
    handleSelectDM,
    handleSelectAssetDump,
    handleSelectAddons,
    handleSelectNostrProfile,
    handleSelectVoiceChannel,
    handleSelectGuildChatHome,
    handleSelectGuildChatFull,
    handleCollapseGuildChatFull,
    unreadCounts,
    unreadRoomCounts,
    conversationOpenTraceId,
    setGuildChatCompact,
    streamImmersive,
    setStreamImmersive,
    guildChatDockState,
    currentGuild,
    guildChat,
    guildChatAvailable,
    guildChatCompact,
    guildChatExpanded,
    showVerifyIdentity,
    conversationName,
    setVersionToast,
    setShowUpdateOverlay,
    setShowVerifyIdentity,
  });
}
