import { useMemo } from 'react';

import { getServerUrl, isInsecureConnection } from '../../api';
import { buildMainLayoutViewStateOptions } from './mainLayoutControllerBindings.mjs';
import { buildMainLayoutViewInput } from './mainLayoutControllerInputs.mjs';
import { buildMainLayoutViewState } from './mainLayoutViewState.mjs';

export function useMainLayoutControllerViewState({
  e2eWarning = false,
  versionToast = null,
  showUpdateOverlay = false,
  latestVersionInfo = null,
  headerState = null,
  updateButtonState = null,
  handleUpdateButtonClick = async () => {},
  showPiP = false,
  conversation = null,
  handleSelectStream = () => {},
  setShowPiP = () => {},
  rooms = [],
  myRooms = [],
  createRoom = () => {},
  joinRoom = () => {},
  renameRoom = () => {},
  deleteRoom = () => {},
  handleSelectRoom = () => {},
  handleSelectDM = () => {},
  handleSelectAssetDump = () => {},
  handleSelectAddons = () => {},
  handleSelectNostrProfile = () => {},
  handleSelectVoiceChannel = () => {},
  handleSelectGuildChatHome = () => {},
  handleSelectGuildChatFull = () => {},
  handleCollapseGuildChatFull = () => {},
  unreadCounts = {},
  unreadRoomCounts = {},
  conversationOpenTraceId = null,
  setGuildChatCompact = () => {},
  streamImmersive = false,
  setStreamImmersive = () => {},
  guildChatDockState = null,
  currentGuild = null,
  guildChat = null,
  guildChatAvailable = false,
  guildChatCompact = false,
  guildChatExpanded = false,
  showVerifyIdentity = false,
  conversationName = '',
  setVersionToast = () => {},
  setShowUpdateOverlay = () => {},
  setShowVerifyIdentity = () => {},
} = {}) {
  const windowObj = typeof window !== 'undefined' ? window : null;

  return useMemo(() => buildMainLayoutViewState(buildMainLayoutViewStateOptions(
    buildMainLayoutViewInput({
      insecureConnection: isInsecureConnection(),
      e2eWarning,
      versionToast,
      showUpdateOverlay,
      latestVersionInfo,
      serverUrl: getServerUrl(),
      headerState,
      updateButtonState,
      handleUpdateButtonClick,
      windowObj,
      showPiP,
      conversation,
      handleSelectStream,
      setShowPiP,
      rooms,
      myRooms,
      createRoom,
      joinRoom,
      renameRoom,
      deleteRoom,
      handleSelectRoom,
      handleSelectDM,
      handleSelectAssetDump,
      handleSelectAddons,
      handleSelectNostrProfile,
      handleSelectVoiceChannel,
      handleSelectGuildChatHome,
      handleSelectGuildChatFull,
      handleCollapseGuildChatFull,
      unreadCounts,
      unreadRoomCounts,
      conversationOpenTraceId,
      setGuildChatCompact,
      streamImmersive,
      setStreamImmersive,
      guildChatDockState,
      currentGuild,
      guildChat,
      guildChatAvailable,
      guildChatCompact,
      guildChatExpanded,
      showVerifyIdentity,
      conversationName,
      setVersionToast,
      setShowUpdateOverlay,
      setShowVerifyIdentity,
    })
  )), [
    e2eWarning,
    versionToast,
    showUpdateOverlay,
    latestVersionInfo,
    headerState,
    updateButtonState,
    handleUpdateButtonClick,
    windowObj,
    showPiP,
    conversation,
    handleSelectStream,
    rooms,
    myRooms,
    createRoom,
    joinRoom,
    renameRoom,
    deleteRoom,
    handleSelectRoom,
    handleSelectDM,
    handleSelectAssetDump,
    handleSelectAddons,
    handleSelectNostrProfile,
    handleSelectVoiceChannel,
    handleSelectGuildChatHome,
    handleSelectGuildChatFull,
    handleCollapseGuildChatFull,
    guildChat?.hasUnreadMention,
    unreadCounts,
    unreadRoomCounts,
    conversationOpenTraceId,
    streamImmersive,
    guildChatDockState,
    currentGuild,
    guildChat,
    guildChatAvailable,
    guildChatCompact,
    guildChatExpanded,
    showVerifyIdentity,
    conversationName,
  ]);
}
