export const styles = {
  container: {
    height: '100vh',
    background: '#050705',
    color: 'var(--text-primary)',
    fontFamily: "'Geist', sans-serif",
    position: 'relative',
    overflow: 'auto',
    display: 'flex',
    flexDirection: 'column',
    transition: 'opacity 0.15s ease',
  },
  titleBar: {
    height: 42,
    minHeight: 42,
    display: 'flex',
    alignItems: 'center',
    background: 'rgba(5, 7, 5, 0.95)',
    borderBottom: '1px solid var(--border)',
    WebkitAppRegion: 'drag',
  },
  winBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    padding: '0 14px',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    transition: 'background 0.15s',
  },
  ambientGlow: {
    position: 'fixed',
    top: '-20%',
    left: '-10%',
    width: '50%',
    height: '60%',
    background: 'radial-gradient(ellipse, rgba(64, 255, 64, 0.04) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  ambientGlow2: {
    position: 'fixed',
    bottom: '-30%',
    right: '-15%',
    width: '60%',
    height: '60%',
    background: 'radial-gradient(ellipse, rgba(64, 255, 64, 0.025) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  inner: {
    position: 'relative',
    zIndex: 1,
    flex: 1,
    padding: '48px 40px',
    maxWidth: 1200,
    margin: '0 auto',
    width: '100%',
    boxSizing: 'border-box',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 40,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 14,
  },
  brandMark: {
    fontSize: 32,
    fontWeight: 700,
    fontFamily: "'Geist', sans-serif",
    color: '#40FF40',
    textShadow: '0 0 20px rgba(64, 255, 64, 0.4), 0 0 40px rgba(64, 255, 64, 0.15)',
    letterSpacing: '-1px',
    margin: 0,
  },
  subtitle: {
    fontSize: 14,
    color: 'var(--text-muted)',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  username: {
    fontSize: 14,
    color: 'var(--text-secondary)',
  },
  logoutBtn: {
    background: 'transparent',
    border: '1px solid rgba(64, 255, 64, 0.1)',
    color: 'var(--text-secondary)',
    padding: '6px 14px',
    borderRadius: 6,
    cursor: 'pointer',
    fontSize: 13,
    fontFamily: "'Geist', sans-serif",
    transition: 'border-color 0.2s, color 0.2s',
  },
  actions: {
    display: 'flex',
    gap: 12,
    marginBottom: 40,
  },
  formGuildBtn: {
    background: '#40FF40',
    color: '#050705',
    border: 'none',
    padding: '10px 24px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: "'Geist', sans-serif",
    transition: 'background 0.2s, box-shadow 0.2s',
  },
  joinBtn: {
    background: 'var(--bg-tertiary)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border)',
    padding: '10px 24px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 500,
    fontFamily: "'Geist', sans-serif",
    transition: 'border-color 0.2s, background 0.2s',
  },
  section: {
    marginBottom: 36,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text-muted)',
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: 12,
  },
  card: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    padding: '18px 20px',
    background: 'linear-gradient(135deg, rgba(14, 17, 14, 0.8), rgba(21, 26, 21, 0.6))',
    border: '1px solid var(--border)',
    borderRadius: 10,
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'border-color 0.2s, box-shadow 0.2s, transform 0.2s, background 0.2s',
    fontFamily: "'Geist', sans-serif",
    backdropFilter: 'blur(8px)',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)',
  },
  cardIcon: {
    width: 48,
    height: 48,
    borderRadius: 10,
    background: 'rgba(64, 255, 64, 0.06)',
    border: '1px solid rgba(64, 255, 64, 0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
  },
  cardImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  cardInitial: {
    fontSize: 20,
    fontWeight: 700,
    color: '#40FF40',
    textShadow: '0 0 8px rgba(64, 255, 64, 0.3)',
  },
  cardInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    minWidth: 0,
  },
  cardName: {
    fontSize: 15,
    fontWeight: 600,
    color: 'var(--text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardMeta: {
    fontSize: 12,
    color: 'var(--text-muted)',
  },
  empty: {
    display: 'flex',
    justifyContent: 'center',
    padding: 80,
  },
  emptyText: {
    color: 'var(--text-muted)',
    fontSize: 15,
  },
  confirmOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  confirmModal: {
    background: 'linear-gradient(135deg, rgba(14, 17, 14, 0.95), rgba(21, 26, 21, 0.95))',
    backdropFilter: 'blur(16px)',
    border: '1px solid var(--border)',
    borderRadius: 16,
    padding: '32px 36px',
    width: 360,
    maxWidth: '90vw',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    fontFamily: "'Geist', sans-serif",
    boxShadow: '0 8px 40px rgba(0, 0, 0, 0.5), 0 0 60px rgba(64, 255, 64, 0.04)',
  },
  confirmIcon: {
    width: 64,
    height: 64,
    borderRadius: 16,
    background: 'rgba(64, 255, 64, 0.06)',
    border: '1px solid rgba(64, 255, 64, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 16,
    boxShadow: '0 0 24px rgba(64, 255, 64, 0.08)',
  },
  confirmInitial: {
    fontSize: 26,
    fontWeight: 700,
    color: '#40FF40',
    textShadow: '0 0 12px rgba(64, 255, 64, 0.3)',
  },
  confirmTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: '0 0 6px',
    textAlign: 'center',
  },
  confirmDesc: {
    fontSize: 13,
    color: 'var(--text-muted)',
    margin: '0 0 24px',
    textAlign: 'center',
  },
  confirmActions: {
    display: 'flex',
    gap: 12,
    width: '100%',
  },
  confirmCancelBtn: {
    flex: 1,
    background: 'transparent',
    border: '1px solid var(--border)',
    color: 'var(--text-secondary)',
    padding: '10px 20px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 500,
    fontFamily: "'Geist', sans-serif",
    transition: 'border-color 0.2s',
  },
  confirmJoinBtn: {
    flex: 1,
    background: '#40FF40',
    color: '#050705',
    border: 'none',
    padding: '10px 20px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: "'Geist', sans-serif",
    transition: 'background 0.2s, box-shadow 0.2s',
  },
};
