export const styles = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.7)',
    backdropFilter: 'blur(4px)',
    WebkitBackdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    background: 'var(--bg-secondary)',
    borderRadius: 12,
    border: '1px solid var(--border)',
    boxShadow: '0 16px 48px rgba(0, 0, 0, 0.5)',
    width: 580,
    maxWidth: '90vw',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column',
    animation: 'fadeIn 0.2s ease-out',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px 0',
  },
  title: {
    fontSize: 16,
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: 0,
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--text-muted)',
    fontSize: 22,
    cursor: 'pointer',
    padding: '0 4px',
    lineHeight: 1,
  },
  tabs: {
    display: 'flex',
    gap: 0,
    padding: '12px 20px 0',
    borderBottom: '1px solid var(--border)',
  },
  tab: {
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    padding: '8px 14px',
    fontSize: 12,
    fontWeight: 500,
    color: 'var(--text-muted)',
    cursor: 'pointer',
    transition: 'color 0.15s, border-color 0.15s',
  },
  tabActive: {
    color: 'var(--accent)',
    borderBottomColor: 'var(--accent)',
  },
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: 20,
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    fontSize: 12,
    fontWeight: 500,
    color: 'var(--text-muted)',
  },
  input: {
    padding: '8px 12px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    fontSize: 13,
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  select: {
    padding: '6px 8px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    fontSize: 12,
    outline: 'none',
    cursor: 'pointer',
  },
  primaryBtn: {
    padding: '10px 16px',
    borderRadius: 6,
    border: 'none',
    background: 'var(--accent)',
    color: '#fff',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'opacity 0.15s',
  },
  primaryBtnSmall: {
    padding: '6px 12px',
    borderRadius: 6,
    border: 'none',
    background: 'var(--accent)',
    color: '#fff',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  },
  secondaryBtn: {
    padding: '10px 16px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'transparent',
    color: 'var(--text-secondary)',
    fontSize: 13,
    cursor: 'pointer',
    transition: 'color 0.15s',
  },
  secondaryBtnSmall: {
    padding: '6px 12px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'transparent',
    color: 'var(--text-secondary)',
    fontSize: 12,
    cursor: 'pointer',
  },
  dangerBtn: {
    padding: '8px 14px',
    borderRadius: 6,
    border: '1px solid var(--danger)',
    background: 'rgba(239, 68, 68, 0.1)',
    color: 'var(--danger)',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  },
  dangerBtnSmall: {
    padding: '6px 10px',
    borderRadius: 6,
    border: '1px solid var(--danger)',
    background: 'transparent',
    color: 'var(--danger)',
    fontSize: 11,
    cursor: 'pointer',
  },
  dangerSmall: {
    background: 'none',
    border: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    padding: 4,
    display: 'flex',
    alignItems: 'center',
    borderRadius: 4,
  },
  memberRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '6px 8px',
    borderRadius: 6,
    transition: 'background 0.15s',
  },
  rankCard: {
    padding: 12,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--bg-tertiary)',
  },
  divider: {
    height: 1,
    background: 'var(--border)',
  },
  error: {
    margin: '8px 20px 0',
    padding: '8px 12px',
    borderRadius: 6,
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid var(--danger)',
    color: 'var(--danger)',
    fontSize: 12,
  },
  success: {
    margin: '8px 20px 0',
    padding: '8px 12px',
    borderRadius: 6,
    background: 'rgba(0, 214, 143, 0.1)',
    border: '1px solid var(--success)',
    color: 'var(--success)',
    fontSize: 12,
  },
  dangerSection: {
    padding: 16,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--bg-tertiary)',
  },
  footer: {
    padding: '12px 20px',
    borderTop: '1px solid var(--border)',
  },
  leaveBtn: {
    background: 'rgba(127, 29, 29, 0.92)',
    border: '1px solid #ef4444',
    color: '#fecaca',
    padding: '8px 16px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "'Geist', sans-serif",
    boxShadow: '0 0 0 1px rgba(239, 68, 68, 0.16), inset 0 1px 0 rgba(255,255,255,0.04)',
    transition: 'background 0.15s, border-color 0.15s, box-shadow 0.15s, color 0.15s',
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 14,
    color: 'var(--text-primary)',
    fontWeight: 400,
  },
  imagePreviewBox: {
    width: 80,
    height: 80,
    borderRadius: 12,
    flexShrink: 0,
    border: '1px solid var(--border)',
    background: 'var(--bg-tertiary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  uploadedImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  uploadBtn: {
    padding: '6px 14px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'var(--bg-tertiary)',
    color: 'var(--text-secondary)',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    display: 'inline-block',
    textAlign: 'center',
  },
  removeBtn: {
    padding: '6px 14px',
    borderRadius: 6,
    background: 'transparent',
    border: '1px solid var(--danger)',
    color: 'var(--danger)',
    fontSize: 12,
    cursor: 'pointer',
    textAlign: 'center',
  },
  confirmOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.6)',
    backdropFilter: 'blur(6px)',
    WebkitBackdropFilter: 'blur(6px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1100,
  },
  confirmModal: {
    background: 'linear-gradient(135deg, rgba(14, 17, 14, 0.95), rgba(21, 26, 21, 0.9))',
    border: '1px solid var(--border)',
    borderRadius: 16,
    padding: '28px 32px',
    width: 380,
    maxWidth: '90vw',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.5)',
    fontFamily: "'Geist', sans-serif",
  },
  confirmTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: '0 0 8px',
  },
  confirmMessage: {
    fontSize: 14,
    color: 'var(--text-secondary)',
    margin: '0 0 24px',
    lineHeight: 1.5,
  },
  confirmActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 12,
  },
  confirmCancelBtn: {
    background: 'transparent',
    border: '1px solid var(--border)',
    color: 'var(--text-secondary)',
    padding: '8px 20px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontFamily: "'Geist', sans-serif",
    transition: 'border-color 0.15s',
  },
  confirmAcceptBtn: {
    background: 'var(--accent)',
    color: '#fff',
    border: 'none',
    padding: '8px 24px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: "'Geist', sans-serif",
  },
  confirmDangerConfirmBtn: {
    background: 'rgba(239, 68, 68, 0.15)',
    color: 'var(--danger)',
    border: '1px solid var(--danger)',
    padding: '8px 24px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: "'Geist', sans-serif",
  },
};
