const MEMBER_TABLE_COLUMNS = '32px minmax(0, 1.25fr) 98px minmax(0, 1.2fr) 96px 54px';

export const guildDashboardStyles = {
  container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    position: 'relative',
  },
  ambientGlow: {
    position: 'absolute',
    top: '-20%',
    left: '-10%',
    width: '50%',
    height: '60%',
    background: 'radial-gradient(ellipse, rgba(64, 255, 64, 0.03) 0%, transparent 70%)',
    pointerEvents: 'none',
    zIndex: 0,
  },
  ambientGlow2: {
    position: 'absolute',
    bottom: '-30%',
    right: '-15%',
    width: '60%',
    height: '60%',
    background: 'radial-gradient(ellipse, rgba(64, 255, 64, 0.02) 0%, transparent 70%)',
    pointerEvents: 'none',
    zIndex: 0,
  },
  scrollArea: {
    flex: 1,
    overflowY: 'auto',
    padding: '16px 24px 24px',
    position: 'relative',
    zIndex: 1,
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    padding: '14px 18px',
    background: 'linear-gradient(135deg, rgba(14, 17, 14, 0.8), rgba(21, 26, 21, 0.6))',
    backdropFilter: 'blur(12px)',
    border: '1px solid var(--border)',
    borderRadius: 14,
    marginBottom: 20,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    minWidth: 0,
  },
  headerCenter: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    padding: '0 16px',
    textAlign: 'center',
  },
  headerRight: {
    flexShrink: 0,
    minWidth: 170,
    maxWidth: 250,
  },
  heroGuildIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: 'rgba(64, 255, 64, 0.06)',
    border: '1px solid rgba(64, 255, 64, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    flexShrink: 0,
    boxShadow: '0 0 20px rgba(64, 255, 64, 0.08)',
  },
  heroGuildImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  heroGuildInitial: {
    fontSize: 18,
    fontWeight: 700,
    color: '#40FF40',
    textShadow: '0 0 12px rgba(64, 255, 64, 0.3)',
  },
  heroGuildName: {
    fontSize: 17,
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: 0,
    lineHeight: 1.2,
    letterSpacing: '-0.3px',
  },
  heroMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    marginTop: 2,
    fontSize: 11,
    color: 'var(--text-secondary)',
  },
  heroDivider: {
    color: 'var(--text-muted)',
  },
  heroOnline: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  headerMotdLabel: {
    fontSize: 9,
    fontWeight: 700,
    color: 'rgba(112, 219, 112, 0.74)',
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    whiteSpace: 'nowrap',
  },
  headerMotdText: {
    maxWidth: '100%',
    fontSize: 12,
    lineHeight: 1.3,
    color: 'rgba(223, 255, 223, 0.92)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  pulseDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: '#40FF40',
    boxShadow: '0 0 6px rgba(64, 255, 64, 0.5)',
    animation: 'subtle-breathe 2s ease-in-out infinite',
    flexShrink: 0,
  },
  section: {
    marginBottom: 18,
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  sectionLabelWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  memberControls: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  memberToggle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    color: 'var(--text-secondary)',
    fontSize: 12,
    cursor: 'pointer',
    userSelect: 'none',
    WebkitUserSelect: 'none',
  },
  memberToggleInput: {
    accentColor: '#40FF40',
    cursor: 'pointer',
  },
  memberExpandIconBtn: {
    width: 24,
    height: 24,
    borderRadius: 999,
    border: '1px solid rgba(64, 255, 64, 0.16)',
    background: 'rgba(10, 15, 10, 0.52)',
    color: 'rgba(215, 255, 215, 0.84)',
    cursor: 'pointer',
    transition: 'border-color 0.15s ease, color 0.15s ease, background 0.15s ease',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  glassCard: {
    padding: '16px 20px',
    background: 'linear-gradient(135deg, rgba(14, 17, 14, 0.7), rgba(21, 26, 21, 0.5))',
    backdropFilter: 'blur(8px)',
    border: '1px solid var(--border)',
    borderRadius: 12,
  },
  statusDisplay: {
    display: 'block',
    width: '100%',
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'rgba(10, 15, 10, 0.5)',
    color: 'var(--text-secondary)',
    fontSize: 12,
    textAlign: 'left',
    cursor: 'pointer',
    transition: 'border-color 0.15s',
    fontFamily: "'Geist', sans-serif",
  },
  statusInputRow: {
    display: 'flex',
    gap: 8,
  },
  statusInput: {
    flex: 1,
    padding: '10px 14px',
    borderRadius: 8,
    border: '1px solid var(--accent)',
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    fontSize: 13,
    outline: 'none',
    fontFamily: "'Geist', sans-serif",
  },
  motdLabel: {
    fontSize: 10,
    fontWeight: 600,
    color: 'var(--accent)',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  motdText: {
    fontSize: 14,
    color: 'var(--text-primary)',
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
  },
  membersList: {
    background: 'linear-gradient(135deg, rgba(14, 17, 14, 0.7), rgba(21, 26, 21, 0.5))',
    backdropFilter: 'blur(8px)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    overflowX: 'auto',
    overflowY: 'hidden',
  },
  memberListHeader: {
    display: 'grid',
    gridTemplateColumns: MEMBER_TABLE_COLUMNS,
    gap: 10,
    alignItems: 'center',
    padding: '6px 12px',
    borderBottom: '1px solid var(--border)',
    fontSize: 9,
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  memberRow: {
    display: 'grid',
    gridTemplateColumns: MEMBER_TABLE_COLUMNS,
    gap: 10,
    alignItems: 'center',
    padding: '6px 12px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.03)',
    transition: 'background 0.1s',
    cursor: 'default',
  },
  memberAvatarWrap: {
    position: 'relative',
    flexShrink: 0,
    width: 26,
    height: 26,
  },
  onlineDot: {
    position: 'absolute',
    bottom: -1,
    right: -1,
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: 'var(--success)',
    border: '1.5px solid #0e120e',
  },
  memberName: {
    minWidth: 0,
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rankBadge: {
    fontSize: 9,
    fontWeight: 500,
    color: 'var(--text-muted)',
    background: 'rgba(64, 255, 64, 0.08)',
    border: '1px solid rgba(64, 255, 64, 0.12)',
    borderRadius: 10,
    padding: '1px 7px',
    whiteSpace: 'nowrap',
    textAlign: 'center',
    width: 'fit-content',
  },
  memberStatusCell: {
    minWidth: 0,
  },
  memberStatusButton: {
    minWidth: 0,
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: 0,
    border: 'none',
    background: 'none',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: 11,
    fontFamily: "'Geist', sans-serif",
    textAlign: 'left',
    transition: 'color 0.15s ease',
  },
  memberStatusText: {
    minWidth: 0,
    flex: 1,
    fontSize: 'inherit',
    color: 'inherit',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  memberStatusIcon: {
    flexShrink: 0,
    opacity: 0.7,
  },
  memberStatusPlaceholder: {
    fontSize: 11,
    color: 'var(--text-muted)',
  },
  memberLastSeenCell: {
    fontSize: 11,
    whiteSpace: 'nowrap',
  },
  memberLinkCell: {
    textAlign: 'right',
  },
  profileLink: {
    fontSize: 10,
    color: 'var(--accent)',
    fontWeight: 500,
    cursor: 'pointer',
  },
  colAvatar: { width: 32 },
  colName: { minWidth: 0 },
  colRank: {},
  colStatus: { minWidth: 0 },
  colLastSeen: {},
  colLink: { textAlign: 'right' },
  statusPopover: {
    position: 'fixed',
    zIndex: 1250,
    width: 'min(360px, calc(100vw - 24px))',
    maxHeight: 'min(240px, calc(100vh - 24px))',
    overflowY: 'auto',
    background: 'rgba(11, 16, 11, 0.98)',
    border: '1px solid rgba(64, 255, 64, 0.12)',
    borderRadius: 12,
    boxShadow: '0 14px 40px rgba(0, 0, 0, 0.45)',
    padding: 14,
    animation: 'fadeIn 0.12s ease-out',
  },
  statusPopoverHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 10,
  },
  statusPopoverUser: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--accent)',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  statusPopoverClose: {
    border: '1px solid var(--border)',
    borderRadius: 999,
    background: 'rgba(255, 255, 255, 0.03)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    padding: '4px 10px',
    fontSize: 11,
    fontFamily: "'Geist', sans-serif",
  },
  statusPopoverText: {
    fontSize: 14,
    color: 'var(--text-primary)',
    lineHeight: 1.65,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    padding: '12px 14px',
    background: 'rgba(10, 15, 10, 0.55)',
    border: '1px solid var(--border)',
    borderRadius: 10,
  },
  statusPopoverHint: {
    marginTop: 10,
    fontSize: 11,
    color: 'var(--text-muted)',
  },
  showMoreBtn: {
    width: '100%',
    padding: '10px 0',
    marginTop: 12,
    background: 'transparent',
    border: '1px solid var(--border)',
    borderRadius: 8,
    color: 'var(--text-secondary)',
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: "'Geist', sans-serif",
    transition: 'border-color 0.15s',
  },
  aboutLink: {
    color: 'var(--accent)',
    cursor: 'pointer',
    fontWeight: 500,
  },
  aboutOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.6)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  aboutModal: {
    background: 'linear-gradient(135deg, rgba(14, 17, 14, 0.95), rgba(21, 26, 21, 0.95))',
    backdropFilter: 'blur(16px)',
    border: '1px solid var(--border)',
    borderRadius: 14,
    width: 440,
    maxWidth: '90vw',
    maxHeight: '70vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 8px 40px rgba(0, 0, 0, 0.5), 0 0 60px rgba(64, 255, 64, 0.04)',
  },
  aboutHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px',
    borderBottom: '1px solid var(--border)',
  },
  aboutTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: 0,
  },
  aboutClose: {
    background: 'none',
    border: 'none',
    color: 'var(--text-muted)',
    fontSize: 22,
    cursor: 'pointer',
    padding: '0 4px',
    lineHeight: 1,
  },
  aboutBody: {
    padding: '20px',
    fontSize: 14,
    color: 'var(--text-secondary)',
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
    overflowY: 'auto',
  },
};
